-- Oracle TPC-DS DDL (subset)
-- Source: https://github.com/litkhai/tpcds-oracle
-- Standard benchmark tables testing complex data type mappings

CREATE TABLE tpcds.customer_address (
    ca_address_sk    INTEGER      NOT NULL,
    ca_address_id    CHAR(16)     NOT NULL,
    ca_street_number CHAR(10),
    ca_street_name   VARCHAR2(60),
    ca_street_type   CHAR(15),
    ca_suite_number  CHAR(10),
    ca_city          VARCHAR2(60),
    ca_county        VARCHAR2(30),
    ca_state         CHAR(2),
    ca_zip           CHAR(10),
    ca_country       VARCHAR2(20),
    ca_gmt_offset    NUMBER(5,2),
    ca_location_type CHAR(20),
    PRIMARY KEY (ca_address_sk)
);

CREATE TABLE tpcds.date_dim (
    d_date_sk        INTEGER  NOT NULL,
    d_date_id        CHAR(16) NOT NULL,
    d_date           DATE,
    d_month_seq      INTEGER,
    d_week_seq       INTEGER,
    d_quarter_seq    INTEGER,
    d_year           INTEGER,
    d_dow            INTEGER,
    d_moy            INTEGER,
    d_dom            INTEGER,
    d_qoy            INTEGER,
    d_fy_year        INTEGER,
    d_fy_quarter_seq INTEGER,
    d_fy_week_seq    INTEGER,
    d_day_name       CHAR(9),
    d_quarter_name   CHAR(6),
    d_holiday        CHAR(1),
    d_weekend        CHAR(1),
    d_following_holiday CHAR(1),
    d_first_dom      INTEGER,
    d_last_dom       INTEGER,
    d_same_day_ly    INTEGER,
    d_same_day_lq    INTEGER,
    d_current_day    CHAR(1),
    d_current_week   CHAR(1),
    d_current_month  CHAR(1),
    d_current_quarter CHAR(1),
    d_current_year   CHAR(1),
    PRIMARY KEY (d_date_sk)
);

CREATE TABLE tpcds.store_sales (
    ss_sold_date_sk      INTEGER,
    ss_sold_time_sk      INTEGER,
    ss_item_sk           INTEGER NOT NULL,
    ss_customer_sk       INTEGER,
    ss_cdemo_sk          INTEGER,
    ss_hdemo_sk          INTEGER,
    ss_addr_sk           INTEGER,
    ss_store_sk          INTEGER,
    ss_promo_sk          INTEGER,
    ss_ticket_number     INTEGER NOT NULL,
    ss_quantity          INTEGER,
    ss_wholesale_cost    NUMBER(7,2),
    ss_list_price        NUMBER(7,2),
    ss_sales_price       NUMBER(7,2),
    ss_ext_discount_amt  NUMBER(7,2),
    ss_ext_sales_price   NUMBER(7,2),
    ss_ext_wholesale_cost NUMBER(7,2),
    ss_ext_list_price    NUMBER(7,2),
    ss_ext_tax           NUMBER(7,2),
    ss_coupon_amt        NUMBER(7,2),
    ss_net_paid          NUMBER(7,2),
    ss_net_paid_inc_tax  NUMBER(7,2),
    ss_net_profit        NUMBER(7,2),
    PRIMARY KEY (ss_item_sk, ss_ticket_number)
);

CREATE TABLE tpcds.item (
    i_item_sk         INTEGER  NOT NULL,
    i_item_id         CHAR(16) NOT NULL,
    i_rec_start_date  DATE,
    i_rec_end_date    DATE,
    i_item_desc       VARCHAR2(200),
    i_current_price   NUMBER(7,2),
    i_wholesale_cost  NUMBER(7,2),
    i_brand_id        INTEGER,
    i_brand           CHAR(50),
    i_class_id        INTEGER,
    i_class           CHAR(50),
    i_category_id     INTEGER,
    i_category        CHAR(50),
    i_manufact_id     INTEGER,
    i_manufact        CHAR(50),
    i_size            CHAR(20),
    i_formulation     CHAR(20),
    i_color           CHAR(20),
    i_units           CHAR(10),
    i_container       CHAR(10),
    i_manager_id      INTEGER,
    i_product_name    CHAR(50),
    PRIMARY KEY (i_item_sk)
);
