CREATE TABLE ${schema}.staging_teacher_test_candidate_progress ( fttcp_dw_id BIGINT, fttcp_session_id Varchar(36), fttcp_candidate_id Varchar(36), fttcp_test_delivery_id Varchar(36), fttcp_assessment_id Varchar(36), fttcp_score FLOAT(53), fttcp_stars_awarded INT, fttcp_status Varchar(50), fttcp_updated_at DATETIME2(6), fttcp_created_at DATETIME2(6), fttcp_date_dw_id BIGINT, fttcp_created_time DATETIME2(6), fttcp_dw_created_time DATETIME2(6) ); 

CREATE TABLE ${schema}.try_date_char ( date_diff Varchar(1000) ); 

CREATE TABLE ${schema}.rel_content_slide ( dw_id BIGINT NOT NULL , event_type Varchar(100), _trace_id Varchar(36), tenant_id Varchar(36), id Varchar(36), created_time DATETIME2(6), dw_created_time DATETIME2(6), status SMALLINT, active_until Varchar(36), section_id Varchar(36), source_id Varchar(36), sequence SMALLINT, show_progressbar BIT, disable_primary_button BIT, is_default_disabled BIT, is_last_slide BIT, widget_id Varchar(50), widget_type Varchar(50), widget_sub_type Varchar(50), widget_version Varchar(5), widget_title Varchar(750), widget_subtitle Varchar(1200), widget_has_passage BIT, widget_video BIT, widget_audio BIT, widget_need_help BIT, widget_submit_limit INT, widget_shuffled BIT, widget_feedback BIT, widget_multiple_answer BIT, _ingestion_type Varchar(10) ) ;

CREATE TABLE ${schema}.rel_course_resource_activity_outcome_association ( craoa_dw_id BIGINT, craoa_created_time DATETIME2(6), craoa_updated_time DATETIME2(6), craoa_dw_created_time DATETIME2(6), craoa_dw_updated_time DATETIME2(6), craoa_status INT, craoa_course_id Varchar(36), craoa_activity_id Varchar(36), craoa_outcome_id Varchar(36), craoa_outcome_type Varchar(50), craoa_curr_id BIGINT, craoa_curr_grade_id BIGINT, craoa_curr_subject_id BIGINT ) ;

CREATE TABLE ${schema}.rel_ic_lesson_association ( rel_ic_lesson_id BIGINT, ic_lesson_created_time DATETIME2(6), ic_lesson_dw_created_time DATETIME2(6), ic_lesson_updated_time DATETIME2(6), ic_lesson_dw_updated_time DATETIME2(6), ic_lesson_status SMALLINT, ic_lesson_attach_status SMALLINT, ic_lesson_type SMALLINT, ic_uuid Varchar(36), lo_uuid Varchar(36) ); 

CREATE TABLE ${schema}.rel_principal ( rel_principal_id BIGINT, principal_created_time DATETIME2(6), principal_updated_time DATETIME2(6), principal_deleted_time DATETIME2(6), principal_dw_created_time DATETIME2(6), principal_dw_updated_time DATETIME2(6), principal_active_until DATETIME2(6), principal_status INT, principal_uuid Varchar(36), principal_onboarded BIT, school_uuid Varchar(36), principal_expirable BIT ) ;

CREATE TABLE ${schema}.staging_pathway_leaderboard ( fpl_staging_id BIGINT , fpl_created_time DATETIME2(6), fpl_dw_created_time DATETIME2(6), fpl_date_dw_id BIGINT, fpl_id Varchar(36), fpl_student_id Varchar(36), fpl_pathway_id Varchar(36), fpl_class_id Varchar(36), fpl_grade_id Varchar(36), fpl_academic_year_id Varchar(36), fpl_start_date DATE, fpl_end_date DATE, fpl_order SMALLINT, fpl_level_competed_count SMALLINT, fpl_average_score FLOAT(53), fpl_total_stars SMALLINT, fpl_tenant_id Varchar(36), fpl_average_proficiency_score FLOAT(53) ) ;

CREATE TABLE ${schema}.staging_student_queries ( dw_id BIGINT, created_time DATETIME2(6), dw_created_time DATETIME2(6), date_dw_id BIGINT, _trace_id Varchar(36), event_type Varchar(36), message_id Varchar(36), query_id Varchar(36), tenant_id Varchar(36), school_id Varchar(36), grade_id Varchar(36), class_id Varchar(36), section_id Varchar(36), teacher_id Varchar(36), academic_year_id Varchar(36), student_id Varchar(36) , mlo_id Varchar(36), activity_id Varchar(36), activity_type Varchar(100), can_student_reply BIT, with_audio BIT, with_text BIT, material_type Varchar(100), gen_subject Varchar(100), lang_code Varchar(100), is_follow_up BIT, has_screenshot BIT, _ingestion_type Varchar(10) ) ;

CREATE TABLE ${schema}.staging_guardian_app_activities ( fgaa_staging_id BIGINT, fgaa_created_time DATETIME2(6), fgaa_actor_object_type Varchar(100), fgaa_actor_account_homepage Varchar(100), fgaa_verb_display Varchar(100), fgaa_verb_id Varchar(100), fgaa_object_id Varchar(2000), fgaa_object_type Varchar(100), fgaa_object_account_homepage Varchar(100), fgaa_dw_created_time DATETIME2(6), fgaa_event_type Varchar(100), fgaa_date_dw_id BIGINT, fgaa_device Varchar(100), tenant_uuid Varchar(36), guardian_uuid Varchar(36), student_uuid Varchar(36), school_uuid Varchar(36), fgaa_timestamp_local Varchar(100) ); 

CREATE TABLE ${schema}.staging_skill_content_unavailable ( scu_staging_id BIGINT, scu_created_time DATETIME2(6), scu_dw_created_time DATETIME2(6), scu_date_dw_id BIGINT, tenant_uuid Varchar(36), lo_uuid Varchar(36), skill_uuid Varchar(36) ); 

CREATE TABLE ${schema}.rel_section_schedule ( rel_section_schedule_id BIGINT, section_schedule_day_of_week Varchar(10), section_schedule_start_time Varchar(20), section_schedule_end_time Varchar(20), section_schedule_created_time DATETIME2(6), section_schedule_updated_time DATETIME2(6), section_schedule_deleted_time DATETIME2(6), section_schedule_dw_created_time DATETIME2(6), section_schedule_dw_updated_time DATETIME2(6), section_schedule_active_until DATETIME2(6), section_schedule_status INT, section_uuid Varchar(36), tenant_uuid Varchar(36), subject_uuid Varchar(36), teacher_uuid Varchar(36) ); 

CREATE TABLE ${schema}.staging_teacher_task_center ( dw_id BIGINT, created_time DATETIME2(6), dw_created_time DATETIME2(6), date_dw_id BIGINT, _trace_id Varchar(36), event_type Varchar(36), event_id Varchar(36), task_id Varchar(36), task_type Varchar(36), tenant_id Varchar(36), school_id Varchar(36), class_id Varchar(36), teacher_id Varchar(36) , _ingestion_type Varchar(10) ) ;

CREATE TABLE ${schema}.staging_weekly_goal ( fwg_dw_id BIGINT, fwg_created_time DATETIME2(6), fwg_dw_created_time DATETIME2(6), fwg_id Varchar(36), fwg_action_status INT, fwg_type_id Varchar(36), fwg_student_id Varchar(36), fwg_tenant_id Varchar(36), fwg_class_id Varchar(36), fwg_star_earned INT, fwg_date_dw_id BIGINT ); 

CREATE TABLE ${schema}.staging_candidate_assessment_progress ( dw_id BIGINT, _trace_id Varchar(36), event_type Varchar(50), created_time DATETIME2(6), dw_created_time DATETIME2(6), date_dw_id BIGINT, tenant_id Varchar(36), academic_year_tag Varchar(20), assessment_id Varchar(36), school_id Varchar(36), grade_id Varchar(36), class_id Varchar(36), candidate_id Varchar(36), grade INT, material_type Varchar(50), attempt_number INT, skill Varchar(20), subject Varchar(50), language Varchar(20), status Varchar(20), test_level_session_id Varchar(36), test_level Varchar(20), test_id Varchar(36), test_version BIGINT, test_level_id Varchar(36), test_level_version BIGINT, test_level_section_id Varchar(36) , report_id Varchar(36), total_timespent BIGINT, final_score BIGINT, final_grade BIGINT, final_category Varchar(20), final_uncertainty FLOAT(53), time_to_return BIGINT, framework Varchar(20), _ingestion_type Varchar(10) ); 

CREATE TABLE ${schema}.staging_challenge_game_progress ( fgc_dw_id BIGINT, fgc_created_time DATETIME2(6), fgc_dw_created_time DATETIME2(6), fgc_date_dw_id BIGINT, fgc_id Varchar(36), fgc_game_id Varchar(36), fgc_state Varchar(20), fgc_tenant_id Varchar(36), fgc_student_id Varchar(36), fgc_academic_year_id Varchar(36), fgc_academic_year_tag Varchar(10), fgc_school_id Varchar(36), fgc_grade INT, fgc_organization Varchar(100), fgc_score INT ); 

CREATE TABLE ${schema}.new_try_date ( practice_session_created_time DATETIME2(6), practice_session_dw_created_time DATETIME2(6) ); 

CREATE TABLE ${schema}.rel_course_activity_association ( caa_dw_id BIGINT, caa_created_time DATETIME2(6), caa_updated_time DATETIME2(6), caa_deleted_time DATETIME2(6), caa_dw_created_time DATETIME2(6), caa_dw_updated_time DATETIME2(6), caa_dw_deleted_time DATETIME2(6), caa_status INT, caa_attach_status INT, caa_course_id Varchar(36), caa_container_id Varchar(36), caa_activity_id Varchar(36), caa_activity_type INT, caa_activity_pacing Varchar(50), caa_activity_index INT, caa_course_version Varchar(10), caa_is_parent_deleted BIT, caa_grade Varchar(10), caa_activity_is_optional BIT, caa_is_joint_parent_activity BIT ); 

CREATE TABLE ${schema}.staging_ktg ( ktg_staging_id BIGINT, ktg_id Varchar(256), ktg_created_time DATETIME2(6), ktg_dw_created_time DATETIME2(6), ktg_date_dw_id BIGINT, tenant_uuid Varchar(36), student_uuid Varchar(36) , subject_uuid Varchar(36), school_uuid Varchar(36), grade_uuid Varchar(36), section_uuid Varchar(36), lo_uuid Varchar(36), academic_year_uuid Varchar(36), ktg_num_key_terms SMALLINT, ktg_kt_collection_id BIGINT, ktg_trimester_id Varchar(256), ktg_trimester_order SMALLINT, ktg_type Varchar(200), ktg_question_type Varchar(200), ktg_min_question SMALLINT, ktg_max_question SMALLINT, ktg_question_time_allotted INT, ktg_instructional_plan_id Varchar(36), ktg_learning_path_id Varchar(36), class_uuid Varchar(36), ktg_material_id Varchar(36), ktg_material_type Varchar(20) ); 

CREATE TABLE ${schema}.rel_content_repository ( rel_content_repository_id BIGINT, content_repository_id Varchar(36), content_repository_name Varchar(50), content_repository_organisation_owner Varchar(50), content_repository_created_time DATETIME2(6), content_repository_dw_created_time DATETIME2(6), content_repository_updated_time DATETIME2(6), content_repository_dw_updated_time DATETIME2(6), content_repository_status INT ) ;

CREATE TABLE ${schema}.staging_tutor_conversation ( ftc_dw_id BIGINT, ftc_created_time DATETIME2(6), ftc_dw_created_time DATETIME2(6), ftc_date_dw_id BIGINT, ftc_tenant_id Varchar(36), ftc_school_id Varchar(36), ftc_user_id Varchar(36), ftc_role Varchar(20), ftc_grade INT, ftc_grade_id Varchar(36), ftc_context_id Varchar(36), ftc_session_id Varchar(36), ftc_subject_id BIGINT, ftc_subject Varchar(20), ftc_language Varchar(20), ftc_activity_id Varchar(36), ftc_activity_status Varchar(20), ftc_material_id Varchar(36), ftc_material_type Varchar(20), ftc_level_id Varchar(36), ftc_outcome_id Varchar(36), ftc_conversation_max_tokens INT, ftc_conversation_token_count INT, ftc_system_prompt_tokens INT, ftc_message_language Varchar(30), ftc_user_message_source Varchar(30), ftc_user_message_tokens INT, ftc_user_message_timestamp DATETIME2(6), ftc_bot_message_source Varchar(30), ftc_bot_message_tokens INT, ftc_bot_message_timestamp DATETIME2(6), ftc_bot_message_confidence FLOAT(53), ftc_bot_message_response_time FLOAT(53), ftc_session_state INT, ftc_session_status Varchar(20), ftc_message_id Varchar(36), ftc_conversation_id Varchar(36), ftc_suggestions_prompt_tokens Varchar(256), ftc_message_tokens Varchar(256), ftc_activity_page_context_id Varchar(256), ftc_student_location Varchar(256), ftc_suggestion_clicked BIT, ftc_clicked_suggestion_id Varchar(36), ftc_message_feedback Varchar(10) ) ;

CREATE TABLE ${schema}.rel_class_backup_20220118 ( rel_class_id BIGINT, class_created_time DATETIME2(6), class_updated_time DATETIME2(6), class_deleted_time DATETIME2(6), class_dw_created_time DATETIME2(6), class_dw_updated_time DATETIME2(6), class_status INT, class_id Varchar(36), class_title Varchar(255), class_school_id Varchar(36), class_grade_id Varchar(36), class_section_id Varchar(36), class_academic_year_id Varchar(36), class_gen_subject Varchar(255), class_curriculum_id BIGINT, class_curriculum_grade_id BIGINT, class_curriculum_subject_id BIGINT, class_content_academic_year INT, class_tutor_dhabi_enabled BIT, class_language_direction Varchar(25), class_online BIT, class_practice BIT, class_course_status Varchar(50), class_source_id Varchar(255), class_curriculum_instructional_plan_id Varchar(36), class_category_id Varchar(36), class_active_until DATETIME2(6) ); 

CREATE TABLE ${schema}.staging_tutor_challenge_question_answer ( ftcqa_bot_question_timestamp DATETIME2(6), ftcqa_bot_question_source Varchar(10), ftcqa_bot_question_id Varchar(36), ftcqa_bot_question_tokens INT, ftcqa_conversation_id Varchar(36), ftcqa_session_id Varchar(36), ftcqa_message_id Varchar(36), ftcqa_user_id Varchar(36), ftcqa_tenant_id Varchar(36), ftcqa_date_dw_id BIGINT, ftcqa_created_time DATETIME2(6), ftcqa_dw_created_time DATETIME2(6), ftcqa_is_answer_evaluated BIT, ftcqa_dw_id BIGINT, ftcqa_user_attempt_tokens INT, ftcqa_user_attempt_number INT, ftcqa_user_remaining_attempts INT, ftcqa_user_attempt_timestamp DATETIME2(6), ftcqa_user_attempt_is_correct BIT, ftcqa_user_attempt_source Varchar(20), ftcqa_user_attempt_id Varchar(36) ); 

CREATE TABLE ${schema}.staging_tutor_user_context ( ftc_dw_id BIGINT, ftc_created_time DATETIME2(6), ftc_dw_created_time DATETIME2(6), ftc_date_dw_id BIGINT, ftc_tenant_id Varchar(36), ftc_user_id Varchar(36), ftc_role Varchar(20), ftc_context_id Varchar(36), ftc_school_id Varchar(36), ftc_grade_id Varchar(36), ftc_grade BIGINT, ftc_subject_id Varchar(36), ftc_subject Varchar(20), ftc_language Varchar(20), ftc_tutor_locked BIT ) ;

CREATE TABLE ${schema}.rel_course_activity_ip_association ( dw_id BIGINT, event_type Varchar(100), created_time DATETIME2(6), dw_created_time DATETIME2(6), active_until DATETIME2(6), status INT, ip_id Varchar(36), course_id Varchar(36), course_type Varchar(255), course_version Varchar(255), course_status Varchar(255), frame_id Varchar(36), frame_is_hidden BIT, parent_container_id Varchar(36), parent_container_title Varchar(255), activity_id Varchar(36), activity_is_joint_parent_activity BIT, activity_type Varchar(255), activity_is_hidden BIT ); 

CREATE TABLE ${schema}.staging_adaptive_practice_progress ( dw_id BIGINT, event_type Varchar(100), _trace_id Varchar(36), tenant_id Varchar(36), date_dw_id BIGINT, uuid Varchar(36), created_time DATETIME2(6), dw_created_time DATETIME2(6), student_id Varchar(36) , class_id Varchar(36), school_id Varchar(36), pathway_id Varchar(36), level_id Varchar(36), academic_year_tag Varchar(40), session_id Varchar(36), ml_session_id Varchar(36), level_proficiency_score FLOAT(53), level_proficiency_tier Varchar(50), assessment_id Varchar(36), session_attempt INT, stars INT, time_spent INT, question_id Varchar(36), question_skill_id Varchar(36), question_difficulty_label Varchar(30), skill_proficiency_tier Varchar(40), skill_proficiency_score FLOAT(53), answer_score FLOAT(53), time_spent_on_question INT, hint_used BIT, is_answer_correct BIT, next_question_id Varchar(36), attempt_number INT, next_question_skill_id Varchar(36), next_question_difficulty_label Varchar(30), _ingestion_type Varchar(10) ); 

CREATE TABLE ${schema}.staging_experience_submitted ( fes_staging_id BIGINT, fes_created_time DATETIME2(6), fes_dw_created_time DATETIME2(6), fes_date_dw_id BIGINT, fes_id Varchar(36), exp_uuid Varchar(36), fes_ls_id Varchar(36), fes_content_id Varchar(36), lo_uuid Varchar(36), student_uuid Varchar(36), section_uuid Varchar(36), class_uuid Varchar(36), subject_uuid Varchar(36), grade_uuid Varchar(36), tenant_uuid Varchar(36), school_uuid Varchar(36), lp_uuid Varchar(36), fes_instructional_plan_id Varchar(36), fes_content_package_id Varchar(36), fes_content_title Varchar(100), fes_content_type Varchar(100), fes_start_time DATETIME2(6), fes_lesson_type Varchar(50), fes_is_retry BIT, fes_outside_of_school BIT, fes_attempt INT, fes_academic_period_order INT, academic_year_uuid Varchar(36), fes_content_academic_year INT, fes_lesson_category Varchar(100), fes_suid Varchar(36), fes_abbreviation Varchar(100), fes_activity_type Varchar(100), fes_activity_component_type Varchar(100), fes_completion_node BIT, fes_main_component BIT, fes_exit_ticket BIT, fes_material_id Varchar(36), fes_material_type Varchar(20) ) ;

CREATE TABLE ${schema}.rel_course_activity_outcome_association ( caoa_dw_id BIGINT, caoa_created_time DATETIME2(6), caoa_updated_time DATETIME2(6), caoa_dw_created_time DATETIME2(6), caoa_dw_updated_time DATETIME2(6), caoa_status INT, caoa_course_id Varchar(36), caoa_activity_id Varchar(36), caoa_outcome_id Varchar(36), caoa_outcome_type Varchar(50), caoa_curr_id BIGINT, caoa_curr_grade_id BIGINT, caoa_curr_subject_id BIGINT ); 

CREATE TABLE ${schema}.staging_ktg_session ( ktg_session_staging_id BIGINT, ktg_session_id Varchar(256), ktg_session_created_time DATETIME2(6), ktg_session_dw_created_time DATETIME2(6), ktg_session_date_dw_id BIGINT, ktg_session_question_id Varchar(256), ktg_session_kt_id Varchar(256), tenant_uuid Varchar(36), student_uuid Varchar(36), subject_uuid Varchar(36), school_uuid Varchar(36), grade_uuid Varchar(36), section_uuid Varchar(36), lo_uuid Varchar(36), academic_year_uuid Varchar(36), ktg_session_outside_of_school BIT, ktg_session_trimester_id Varchar(256), ktg_session_trimester_order SMALLINT, ktg_session_type Varchar(200), ktg_session_question_time_allotted INT, ktg_session_answer Varchar(5000), ktg_session_num_attempts SMALLINT, ktg_session_score FLOAT(53), ktg_session_max_score FLOAT(53), ktg_session_stars INT, ktg_session_is_attended BIT, ktg_session_event_type INT, ktg_session_is_start BIT, ktg_session_is_start_event_processed BIT, ktg_session_instructional_plan_id Varchar(36), ktg_session_learning_path_id Varchar(36), class_uuid Varchar(36), ktg_session_material_id Varchar(36), ktg_session_material_type Varchar(20) ); 

CREATE TABLE ${schema}.staging_tutor_onboarding ( fto_dw_id BIGINT, fto_created_time DATETIME2(6), fto_dw_created_time DATETIME2(6), fto_date_dw_id BIGINT, fto_user_id Varchar(36), fto_tenant_id Varchar(36), fto_question_id Varchar(36), fto_question_category Varchar(50), fto_user_free_text_response BIT, fto_onboarding_complete BIT, fto_onboarding_skipped BIT ); 

CREATE TABLE ${schema}.staging_pathway_skill_gap_tracker ( dw_id BIGINT, event_type Varchar(100), _trace_id Varchar(36), tenant_id Varchar(36), date_dw_id BIGINT, uuid Varchar(36), created_time DATETIME2(6), dw_created_time DATETIME2(6), student_id Varchar(36) , class_id Varchar(36), school_id Varchar(36), pathway_id Varchar(36), level_id Varchar(36), academic_year_tag Varchar(40), session_id Varchar(36), ml_session_id Varchar(36), level_proficiency_score FLOAT(53), level_proficiency_tier Varchar(50), assessment_id Varchar(36), session_attempt INT, stars INT, time_spent INT, skill_proficiency_tier Varchar(40), skill_proficiency_score FLOAT(53), skill_id Varchar(36), status Varchar(50), _ingestion_type Varchar(10) ); 

CREATE TABLE ${schema}.staging_item_purchase ( fip_dw_id BIGINT, fip_created_time DATETIME2(6), fip_dw_created_time DATETIME2(6), fip_date_dw_id BIGINT, fip_id Varchar(36), fip_item_id Varchar(36), fip_item_type Varchar(50), fip_item_title Varchar(50), fip_item_description Varchar(50), fip_transaction_id Varchar(36), fip_school_id Varchar(36), fip_grade_id Varchar(36), fip_section_id Varchar(36), fip_academic_year_id Varchar(36), fip_academic_year INT, fip_student_id Varchar(36), fip_tenant_id Varchar(36), fip_redeemed_stars INT ); 

CREATE TABLE ${schema}.staging_student_certificate_awarded ( fsca_dw_id BIGINT, fsca_created_time DATETIME2(6), fsca_dw_created_time DATETIME2(6), fsca_date_dw_id BIGINT, fsca_certificate_id Varchar(36), fsca_student_id Varchar(36), fsca_award_category Varchar(50), fsca_award_purpose Varchar(100), fsca_academic_year_id Varchar(36), fsca_class_id Varchar(36), fsca_grade_id Varchar(36), fsca_teacher_id Varchar(36), fsca_language Varchar(36), fsca_tenant_id Varchar(36) ) ;

CREATE TABLE ${schema}.rel_tdc ( rel_tdc_id BIGINT, tdc_created_time DATETIME2(6), tdc_updated_time DATETIME2(6), tdc_deleted_time DATETIME2(6), tdc_dw_created_time DATETIME2(6), tdc_dw_updated_time DATETIME2(6), tdc_active_until DATETIME2(6), tdc_status INT, tdc_uuid Varchar(36), tdc_onboarded BIT, school_uuid Varchar(36), tdc_expirable BIT ) ;

CREATE TABLE ${schema}.rel_question_pool_association ( rel_question_pool_association_id BIGINT, question_pool_association_created_time DATETIME2(6), question_pool_association_updated_time DATETIME2(6), question_pool_association_dw_created_time DATETIME2(6), question_pool_association_dw_updated_time DATETIME2(6), question_pool_association_status INT, question_pool_association_assign_status INT, question_pool_association_question_code Varchar(120), question_pool_uuid Varchar(36), question_pool_association_triggered_by Varchar(100) ) ;

CREATE TABLE ${schema}.rel_course_activity_grade_association ( caga_dw_id BIGINT, caga_created_time DATETIME2(6), caga_updated_time DATETIME2(6), caga_deleted_time DATETIME2(6), caga_dw_created_time DATETIME2(6), caga_dw_updated_time DATETIME2(6), caga_dw_deleted_time DATETIME2(6), caga_status INT, caga_course_id Varchar(36), caga_activity_id Varchar(36), caga_grade_id Varchar(36) ); 

CREATE TABLE ${schema}.staging_levels_recommended ( flr_dw_id BIGINT, flr_created_time DATETIME2(6), flr_dw_created_time DATETIME2(6), flr_date_dw_id BIGINT, flr_recommended_on DATETIME2(6), flr_tenant_id Varchar(36), flr_student_id Varchar(36), flr_class_id Varchar(36), flr_pathway_id Varchar(36), flr_completed_level_id Varchar(36), flr_level_id Varchar(36), flr_status INT, flr_recommendation_type INT, flr_academic_year Varchar(50) ) ;

CREATE TABLE ${schema}.rel_course_subject_association ( cs_dw_id BIGINT, cs_course_dw_id BIGINT, cs_course_id Varchar(36), cs_subject_id INT, cs_status INT, cs_created_time DATETIME2(6), cs_dw_created_time DATETIME2(6), cs_updated_time DATETIME2(6), cs_dw_updated_time DATETIME2(6) ); 

CREATE TABLE ${schema}.staging_user_avatar ( fua_dw_id BIGINT, fua_created_time DATETIME2(6), fua_dw_created_time DATETIME2(6), fua_date_dw_id BIGINT, fua_id Varchar(255), fua_user_id Varchar(72), fua_tenant_id Varchar(36), fua_school_id Varchar(36), fua_grade_id Varchar(36), fua_avatar_type Varchar(36), fua_avatar_file_id Varchar(36) ); 

CREATE TABLE ${schema}.staging_content_session ( fcs_staging_id BIGINT, fcs_created_time DATETIME2(6), fcs_dw_created_time DATETIME2(6), fcs_date_dw_id BIGINT, fcs_id Varchar(36), fcs_event_type SMALLINT, fcs_is_start BIT, fcs_ls_id Varchar(36), fcs_content_id Varchar(36), fcs_lo_id Varchar(36), fcs_student_id Varchar(36), fcs_class_id Varchar(36), fcs_grade_id Varchar(36), fcs_tenant_id Varchar(36), fcs_school_id Varchar(36), fcs_ay_id Varchar(36), fcs_section_id Varchar(36), fcs_lp_id Varchar(108), fcs_ip_id Varchar(36), fcs_outside_of_school BIT, fcs_content_academic_year Varchar(4), fcs_app_timespent FLOAT(53), fcs_app_score FLOAT(53) ); 

CREATE TABLE ${schema}.staging_assessment_answer_submitted ( dw_id BIGINT, _trace_id Varchar(36), event_type Varchar(100), created_time DATETIME2(6), dw_created_time DATETIME2(6), date_dw_id BIGINT, assessment_id Varchar(36), tenant_id Varchar(36), academic_year_tag Varchar(10), attempt_number INT, candidate_id Varchar(36), class_id Varchar(36), grade INT, grade_id Varchar(36), time_spent INT, subject Varchar(10), school_id Varchar(36), language Varchar(10), question_id Varchar(36), question_code Varchar(50), question_version INT, test_level_session_id Varchar(36), test_level_id Varchar(36), test_level_version BIGINT, test_level_section_id Varchar(36) , reference_code Varchar(50), test_level Varchar(20), skill Varchar(20), material_type Varchar(20), _ingestion_type Varchar(10) ); 

CREATE TABLE ${schema}.try_date ( date_diff BIGINT ); 

CREATE TABLE ${schema}.rel_class ( class_created_time DATETIME2(6), class_updated_time DATETIME2(6), class_deleted_time DATETIME2(6), class_dw_created_time DATETIME2(6), class_dw_updated_time DATETIME2(6), class_status INT, class_id Varchar(36), class_title Varchar(255), class_school_id Varchar(36), class_grade_id Varchar(36), class_section_id Varchar(36), class_academic_year_id Varchar(36), class_gen_subject Varchar(255), class_curriculum_id BIGINT, class_curriculum_grade_id BIGINT, class_curriculum_subject_id BIGINT, class_content_academic_year INT, class_tutor_dhabi_enabled BIT, class_language_direction Varchar(25), class_online BIT, class_practice BIT, class_course_status Varchar(50), class_source_id Varchar(255), class_curriculum_instructional_plan_id Varchar(36), class_category_id Varchar(36), class_active_until DATETIME2(6), class_material_id Varchar(36), class_material_type Varchar(20), rel_class_dw_id BIGINT, class_academic_calendar_id Varchar(36) ); 

CREATE TABLE ${schema}.rel_course_activity_container ( course_activity_container_is_accelerated BIT, course_activity_container_pacing Varchar(50), course_activity_container_grade Varchar(10), course_activity_container_sequence INT, course_activity_container_course_version Varchar(10), course_activity_container_attach_status INT, course_activity_container_id Varchar(36), course_activity_container_longname Varchar(255), course_activity_container_updated_time DATETIME2(6), course_activity_container_dw_created_time DATETIME2(6), course_activity_container_title Varchar(50), course_activity_container_created_time DATETIME2(6), course_activity_container_course_id Varchar(36), course_activity_container_domain Varchar(50), course_activity_container_status INT, course_activity_container_dw_updated_time DATETIME2(6), course_activity_container_index INT, rel_course_activity_container_dw_id BIGINT ); 

CREATE TABLE ${schema}.staging_tutor_suggestions ( fts_dw_id BIGINT, fts_message_id Varchar(36), fts_suggestion_id Varchar(36), fts_created_time DATETIME2(6), fts_dw_created_time DATETIME2(6), fts_user_id Varchar(36), fts_session_id Varchar(36), fts_conversation_id Varchar(36), fts_response_time FLOAT(53), fts_success_parser_tokens INT, fts_failure_parser_tokens INT, fts_suggestion_clicked BIT, fts_date_dw_id BIGINT, fts_tenant_id Varchar(36) ); 

CREATE TABLE ${schema}.rel_lesson_assignment ( rel_lesson_assignment_id BIGINT, lesson_assignment_created_time DATETIME2(6), lesson_assignment_updated_time DATETIME2(6), lesson_assignment_dw_created_time DATETIME2(6), lesson_assignment_dw_updated_time DATETIME2(6), lesson_assignment_status INT, student_uuid Varchar(36), lo_uuid Varchar(36), class_uuid Varchar(36), teacher_uuid Varchar(36), lesson_assignment_assign_status INT, lesson_assignment_type INT ) ;

CREATE TABLE ${schema}.staging_user_login ( ful_staging_id BIGINT, ful_created_time DATETIME2(6), ful_dw_created_time DATETIME2(6), ful_date_dw_id BIGINT, ful_id Varchar(36), user_uuid Varchar(36) , role_uuid Varchar(36), tenant_uuid Varchar(36), school_uuid Varchar(36), ful_outside_of_school BIT, ful_login_time DATETIME2(6) ) ;

CREATE TABLE ${schema}.staging_pathway_activity_completed ( fpac_dw_id BIGINT , fpac_created_time DATETIME2(6), fpac_dw_created_time DATETIME2(6), fpac_date_dw_id BIGINT, fpac_tenant_id Varchar(36), fpac_student_id Varchar(36), fpac_class_id Varchar(36), fpac_pathway_id Varchar(36), fpac_level_id Varchar(36), fpac_activity_id Varchar(36), fpac_activity_type INT, fpac_score FLOAT(53), fpac_learning_session_id Varchar(36), fpac_attempt INT, fpac_academic_year Varchar(50), fpac_time_spent INT ) ;

CREATE TABLE ${schema}.staging_ebook_progress ( fep_dw_id BIGINT, fep_id Varchar(36), fep_created_time DATETIME2(6), fep_dw_created_time DATETIME2(6), fep_date_dw_id BIGINT, fep_session_id Varchar(36), fep_exp_id Varchar(36), fep_student_id Varchar(36), feb_ay_tag Varchar(10), fep_tenant_id Varchar(36), fep_school_id Varchar(36), fep_grade_id Varchar(36), fep_class_id Varchar(36), fep_lo_id Varchar(36), fep_step_instance_step_id Varchar(36), fep_content_hash Varchar(256), fep_material_type Varchar(20), fep_title Varchar(512), fep_total_pages INT, fep_has_audio BIT, fep_action Varchar(50), fep_is_last_page BIT, fep_location Varchar(100), fep_state Varchar(50), fep_time_spent DECIMAL(18,0), fep_bookmark_location Varchar(255), fep_highlight_location Varchar(255) ); 

CREATE TABLE ${schema}.rel_user ( user_dw_id BIGINT, user_id Varchar(36) , user_type Varchar(50), user_created_time DATETIME2(6), user_dw_created_time DATETIME2(6) ) ;

CREATE TABLE ${schema}.rel_course_activity_container_grade_association ( cacga_dw_id BIGINT, cacga_container_id Varchar(36), cacga_course_id Varchar(36), cacga_grade Varchar(10), cacga_created_time DATETIME2(6), cacga_dw_created_time DATETIME2(6), cacga_updated_time DATETIME2(6), cacga_dw_updated_time DATETIME2(6), cacga_status INT ); 

CREATE TABLE ${schema}.staging_pathway_skill_learning_progress ( dw_id BIGINT, event_type Varchar(100), uuid Varchar(36), _trace_id Varchar(36), tenant_id Varchar(36), date_dw_id BIGINT, created_time DATETIME2(6), dw_created_time DATETIME2(6), skill_session_id Varchar(36), experience_id Varchar(36), time_spent_on_activity INT, time_spent_this_time_on_activity INT, component_id Varchar(36), class_id Varchar(36), school_id Varchar(36), student_id Varchar(36) , skill_id Varchar(36), material_id Varchar(36), academic_year Varchar(40), skill_completion_percentage FLOAT(53), is_activity_completed BIT, _ingestion_type Varchar(10) ); 

CREATE TABLE ${schema}.rel_teacher ( rel_teacher_id BIGINT, teacher_created_time DATETIME2(6), teacher_updated_time DATETIME2(6), teacher_deleted_time DATETIME2(6), teacher_dw_created_time DATETIME2(6), teacher_dw_updated_time DATETIME2(6), teacher_active_until DATETIME2(6), teacher_status INT, teacher_id Varchar(36) , subject_id Varchar(36), school_id Varchar(36) ) ;

CREATE TABLE ${schema}.staging_lesson_feedback ( lesson_feedback_staging_id BIGINT, lesson_feedback_id Varchar(36), lesson_feedback_created_time DATETIME2(6), lesson_feedback_dw_created_time DATETIME2(6), lesson_feedback_date_dw_id BIGINT, tenant_uuid Varchar(36), school_uuid Varchar(36), academic_year_uuid Varchar(36), grade_uuid Varchar(36), section_uuid Varchar(36), subject_uuid Varchar(36), student_uuid Varchar(36), lo_uuid Varchar(36), curr_uuid Varchar(36), curr_grade_uuid Varchar(36), curr_subject_uuid Varchar(36), fle_ls_uuid Varchar(36), lesson_feedback_trimester_id Varchar(36), lesson_feedback_trimester_order INT, lesson_feedback_content_academic_year INT, lesson_feedback_rating INT, lesson_feedback_rating_text Varchar(36), lesson_feedback_has_comment BIT, lesson_feedback_is_cancelled BIT, lesson_feedback_instructional_plan_id Varchar(36), lesson_feedback_learning_path_id Varchar(36), class_uuid Varchar(36), lesson_feedback_teaching_period_id Varchar(36), lesson_feedback_teaching_period_title Varchar(50) ); 

CREATE TABLE ${schema}.rel_student ( rel_student_id BIGINT, student_created_time DATETIME2(6), student_updated_time DATETIME2(6), student_deleted_time DATETIME2(6), student_dw_created_time DATETIME2(6), student_dw_updated_time DATETIME2(6), student_active_until DATETIME2(6), student_status INT, student_uuid Varchar(36) , student_username Varchar(256), school_uuid Varchar(36), grade_uuid Varchar(36), section_uuid Varchar(36), student_tags Varchar(256), student_special_needs Varchar(1000) ); 

CREATE TABLE ${schema}.rel_adt_attempt_threshold ( aat_dw_id BIGINT, aat_created_time DATETIME2(6), aat_updated_time DATETIME2(6), aat_dw_created_time DATETIME2(6), aat_dw_updated_time DATETIME2(6), aat_status INT, aat_id Varchar(36), aat_academic_year_id Varchar(36), aat_tenant_id Varchar(36), aat_school_id Varchar(36), aat_state Varchar(50), aat_attempt_title Varchar(100), aat_attempt_start_time DATETIME2(6), aat_attempt_end_time DATETIME2(6), aat_attempt_number INT, aat_total_attempts INT ); 

CREATE TABLE ${schema}.rel_core_activity_assign ( cta_dw_id BIGINT, cta_event_type Varchar(100), cta_id Varchar(36), cta_created_time DATETIME2(6), cta_dw_created_time DATETIME2(6), cta_status SMALLINT, cta_active_until DATETIME2(6), cta_action_time DATETIME2(6), cta_start_date Varchar(10), cta_end_date Varchar(10), cta_ay_tag Varchar(10), cta_tenant_id Varchar(36), cta_student_id Varchar(36) , cta_course_id Varchar(36), cta_class_id Varchar(36), cta_teacher_id Varchar(36), cta_activity_id Varchar(36), cta_activity_type Varchar(20), cta_progress_status Varchar(30) ) ;

CREATE TABLE ${schema}.rel_instructional_plan ( rel_instructional_plan_id BIGINT, instructional_plan_created_time DATETIME2(6), instructional_plan_updated_time DATETIME2(6), instructional_plan_deleted_time DATETIME2(6), instructional_plan_dw_created_time DATETIME2(6), instructional_plan_dw_updated_time DATETIME2(6), instructional_plan_status INT, instructional_plan_id Varchar(36), instructional_plan_name Varchar(100), instructional_plan_curriculum_id BIGINT, instructional_plan_curriculum_subject_id BIGINT, instructional_plan_curriculum_grade_id BIGINT, instructional_plan_content_academic_year_id INT, instructional_plan_item_order INT, week_uuid Varchar(36), lo_uuid Varchar(36), instructional_plan_item_ccl_lo_id BIGINT, instructional_plan_item_optional BIT, instructional_plan_item_instructor_led BIT, instructional_plan_item_default_locked BIT, instructional_plan_item_type Varchar(36), ic_uuid Varchar(36), instructional_plan_content_repository_id Varchar(36), content_repository_uuid Varchar(36) ); 

CREATE TABLE ${schema}.staging_adt_student_report ( fasr_staging_id BIGINT, fasr_created_time DATETIME2(6), fasr_dw_created_time DATETIME2(6), fasr_date_dw_id BIGINT, fasr_tenant_id Varchar(36), fasr_student_id Varchar(36), fasr_question_pool_id Varchar(36), fasr_fle_ls_id Varchar(36), fasr_id Varchar(36), fasr_final_score FLOAT(53), fasr_final_proficiency FLOAT(53), fasr_final_result Varchar(20), fasr_total_time_spent FLOAT(53), fasr_academic_year INT, fasr_academic_term INT, fasr_test_id Varchar(36), fasr_curriculum_subject_id BIGINT, fasr_curriculum_subject_name Varchar(255), fasr_status INT, fasr_final_uncertainty FLOAT(53), fasr_framework Varchar(36), fasr_final_standard_error FLOAT(53), fasr_language Varchar(50), fasr_school_id Varchar(36), fasr_attempt INT, fasr_final_grade INT, fasr_forecast_score FLOAT(53), fasr_final_category Varchar(50), fasr_grade INT, fasr_grade_id Varchar(36), fasr_academic_year_id Varchar(36), fasr_secondary_result Varchar(50), fasr_class_subject_name Varchar(64), fasr_skill Varchar(20) ); 

CREATE TABLE ${schema}.rel_class_user ( class_user_created_time DATETIME2(6), class_user_updated_time DATETIME2(6), class_user_deleted_time DATETIME2(6), class_user_dw_created_time DATETIME2(6), class_user_dw_updated_time DATETIME2(6), class_user_active_until DATETIME2(6), class_user_status INT, class_uuid Varchar(36) , user_uuid Varchar(36), role_uuid Varchar(20), class_user_attach_status INT, rel_class_user_dw_id BIGINT ); 

CREATE TABLE ${schema}.staging_conversation_occurred ( fco_staging_id BIGINT, fco_created_time DATETIME2(6), fco_dw_created_time DATETIME2(6), fco_date_dw_id BIGINT, fco_id Varchar(36), student_uuid Varchar(36), school_uuid Varchar(36), tenant_uuid Varchar(36), grade_uuid Varchar(36), subject_uuid Varchar(36), section_uuid Varchar(36), lo_uuid Varchar(36), fco_answer_id Varchar(36), fco_source Varchar(256), fco_question Varchar(6138), fco_suggestions VARCHAR(MAX), fco_answer Varchar(3000), fco_arabic_answer Varchar(3000), fco_learning_session_id Varchar(36), fco_subject_category Varchar(256) ) ;

CREATE TABLE ${schema}.staging_adt_lock_status ( dw_id BIGINT, _trace_id Varchar(36), event_type Varchar(36), created_time DATETIME2(6), dw_created_time DATETIME2(6), date_dw_id BIGINT, id Varchar(36), tenant_id Varchar(36), academic_year_tag Varchar(10), attempt_number BIGINT, teacher_id Varchar(36), student_id Varchar(36) , school_id Varchar(36), class_id Varchar(36), adt_id Varchar(36), should_send_notification BIT, _ingestion_type Varchar(10), source Varchar(10) ); 

CREATE TABLE ${schema}.staging_guardian_joint_activity ( fgja_staging_id BIGINT, fgja_created_time DATETIME2(6), fgja_dw_created_time DATETIME2(6), fgja_date_dw_id BIGINT, fgja_tenant_id Varchar(256), fgja_school_id Varchar(256), fgja_k12_grade INT, fgja_class_id Varchar(256), fgja_student_id Varchar(256), fgja_guardian_id Varchar(256), fgja_pathway_id Varchar(256), fgja_pathway_level_id Varchar(256), fgja_attempt SMALLINT, fgja_rating SMALLINT, fgja_state SMALLINT ) ;

CREATE TABLE ${schema}.staging_student_proficiency_tracker ( dw_id BIGINT, event_type Varchar(100), _trace_id Varchar(36), tenant_id Varchar(36), date_dw_id BIGINT, uuid Varchar(36), created_time DATETIME2(6), dw_created_time DATETIME2(6), student_id Varchar(36) , class_id Varchar(36), school_id Varchar(36), pathway_id Varchar(36), level_id Varchar(36), academic_year_tag Varchar(40), session_id Varchar(36), ml_session_id Varchar(36), level_proficiency_score FLOAT(53), level_proficiency_tier Varchar(50), assessment_id Varchar(36), session_attempt INT, stars INT, time_spent INT, skill_proficiency_tier Varchar(40), skill_proficiency_score FLOAT(53), skill_id Varchar(36), status Varchar(50), previous_proficiency_tier Varchar(50), _ingestion_type Varchar(10) ); 

CREATE TABLE ${schema}.rel_interim_checkpoint_rules ( rel_ic_rule_id BIGINT, ic_rule_created_time DATETIME2(6), ic_rule_dw_created_time DATETIME2(6), ic_rule_updated_time DATETIME2(6), ic_rule_dw_updated_time DATETIME2(6), ic_rule_status SMALLINT, ic_rule_attach_status SMALLINT, ic_rule_type SMALLINT, ic_rule_resource_type Varchar(50), ic_uuid Varchar(36), outcome_uuid Varchar(36), ic_rule_no_questions INT ); 

CREATE TABLE ${schema}.rel_pathway_target ( pt_dw_id BIGINT, pt_id Varchar(36), pt_created_time DATETIME2(6), pt_dw_created_time DATETIME2(6), pt_status INT, pt_active_until DATETIME2(6), pt_target_id Varchar(36), pt_target_state Varchar(20), pt_start_date Varchar(10), pt_end_date Varchar(10), pt_tenant_id Varchar(36), pt_school_id Varchar(36), pt_grade_id Varchar(36), pt_class_id Varchar(36), pt_teacher_id Varchar(36) , pt_pathway_id Varchar(36) ) ;

CREATE TABLE ${schema}.dim_course_activity_grade_association ( caga_dw_id BIGINT, caga_created_time DATETIME2(6), caga_updated_time DATETIME2(6), caga_deleted_time DATETIME2(6), caga_dw_created_time DATETIME2(6), caga_dw_updated_time DATETIME2(6), caga_dw_deleted_time DATETIME2(6), caga_status INT, caga_course_dw_id BIGINT, caga_course_id Varchar(36), caga_activity_dw_id BIGINT, caga_activity_id Varchar(36), caga_grade_id BIGINT ); 

CREATE TABLE ${schema}.rel_assignment_instance_student ( rel_ais_id BIGINT, ais_created_time DATETIME2(6), ais_dw_created_time DATETIME2(6), ais_updated_time DATETIME2(6), ais_dw_updated_time DATETIME2(6), ais_deleted_time DATETIME2(6), ais_status INT, ais_instance_id Varchar(36), ais_student_id Varchar(36) ); 

CREATE TABLE ${schema}.rel_school_content_repository_association ( scra_dw_id BIGINT, scra_school_id Varchar(36), scra_content_repository_id Varchar(36), scra_status INT, scra_active_until DATETIME2(6), scra_created_time DATETIME2(6), scra_dw_created_time DATETIME2(6) ); 

CREATE TABLE ${schema}.rel_assignment_instance ( assignment_instance_staging_id BIGINT, assignment_instance_created_time DATETIME2(6), assignment_instance_updated_time DATETIME2(6), assignment_instance_deleted_time DATETIME2(6), assignment_instance_dw_created_time DATETIME2(6), assignment_instance_dw_updated_time DATETIME2(6), assignment_instance_id Varchar(36), assignment_instance_instructional_plan_id Varchar(36), assignment_uuid Varchar(36), assignment_instance_due_on DATETIME2(6), assignment_instance_allow_late_submission BIT, teacher_uuid Varchar(36), assignment_instance_type Varchar(10), grade_uuid Varchar(36), subject_uuid Varchar(36), class_uuid Varchar(36), learning_path_uuid Varchar(36), lo_uuid Varchar(36), section_uuid Varchar(36), assignment_instance_start_on DATETIME2(6), assignment_instance_status INT, student_uuid Varchar(36), tenant_uuid Varchar(36), assignment_instance_trimester_id Varchar(36), assignment_instance_teaching_period_id Varchar(36) ) ;

CREATE TABLE ${schema}.rel_dw_id_mappings ( dw_id BIGINT, id Varchar(36) , entity_type Varchar(50), entity_dw_created_time DATETIME2(6), entity_created_time DATETIME2(6) ) ;

CREATE TABLE ${schema}.staging_assessment_lock_action ( dw_id BIGINT, _trace_id Varchar(36), event_type Varchar(36), created_time DATETIME2(6), dw_created_time DATETIME2(6), date_dw_id BIGINT, id Varchar(36), tenant_id Varchar(36), academic_year_tag Varchar(10), attempt BIGINT, teacher_id Varchar(36) , candidate_id Varchar(36), school_id Varchar(36), class_id Varchar(36), test_part_session_id Varchar(36), test_level_name Varchar(20), test_level_id Varchar(36), test_level_version BIGINT, skill Varchar(50), subject Varchar(50), _ingestion_type Varchar(10) ); 

CREATE TABLE ${schema}.rel_course ( rel_course_dw_id BIGINT, course_type Varchar(25), course_id Varchar(36), course_status INT, course_name Varchar(255), course_code Varchar(50), course_subject_id INT, course_organization Varchar(50), course_created_time DATETIME2(6), course_deleted_time DATETIME2(6), course_updated_time DATETIME2(6), course_dw_created_time DATETIME2(6), course_dw_updated_time DATETIME2(6), course_dw_deleted_time DATETIME2(6), course_lang_code Varchar(10), course_program_enabled BIT, course_resources_enabled BIT, course_placement_type Varchar(50) ); 

CREATE TABLE ${schema}.staging_activity_setting ( fas_activity_id Varchar(36), fas_class_id Varchar(36), fas_created_time DATETIME2(6), fas_dw_created_time DATETIME2(6), fas_dw_id BIGINT, fas_grade_id Varchar(36), fas_k12_grade INT, fas_open_path_enabled BIT, fas_school_id Varchar(36), fas_class_gen_subject_name Varchar(50), fas_teacher_id Varchar(36), fas_tenant_id Varchar(36) ); 

CREATE TABLE ${schema}.staging_item_transaction ( fit_dw_id BIGINT, fit_created_time DATETIME2(6), fit_dw_created_time DATETIME2(6), fit_date_dw_id BIGINT, fit_id Varchar(36), fit_available_stars INT, fit_item_cost INT, fit_star_balance INT, fit_item_id Varchar(36), fit_item_type Varchar(50), fit_student_id Varchar(36), fit_tenant_id Varchar(36), fit_school_id Varchar(36), fit_grade_id Varchar(36), fit_section_id Varchar(36), fit_academic_year_id Varchar(36), fit_academic_year INT ); 

CREATE TABLE ${schema}.example_table ( id INT, data VARCHAR(MAX) ); 

CREATE TABLE ${schema}.rel_announcement ( rel_announcement_dw_id BIGINT, announcement_created_time DATETIME2(6), announcement_deleted_time DATETIME2(6), announcement_updated_time DATETIME2(6), announcement_dw_created_time DATETIME2(6), announcement_dw_updated_time DATETIME2(6), announcement_status INT, announcement_tenant_id Varchar(36), announcement_id Varchar(36), announcement_admin_id Varchar(36), announcement_role_id Varchar(36), announcement_recipient_type INT, announcement_recipient_id Varchar(36), announcement_has_attachment BIT ); 

CREATE TABLE ${schema}.staging_pathway_placement ( fpp_staging_id BIGINT , fpp_created_time DATETIME2(6), fpp_dw_created_time DATETIME2(6), fpp_date_dw_id BIGINT, fpp_previous_pathway_domain Varchar(100), fpp_pathway_id Varchar(36), fpp_new_pathway_domain Varchar(100), fpp_new_pathway_grade INT, fpp_class_id Varchar(36), fpp_student_id Varchar(36), fpp_previous_pathway_grade INT, fpp_tenant_id Varchar(36), fpp_placement_type INT, fpp_overall_grade INT, fpp_created_by Varchar(36), fpp_is_initial BIT , fpp_has_accelerated_domains BIT, fpp_academic_year_tag Varchar(40) ) ;

CREATE TABLE ${schema}.rel_course_activity_container_domain ( cacd_dw_id BIGINT, cacd_container_id Varchar(36), cacd_course_id Varchar(36), cacd_domain Varchar(50), cacd_sequence INT, cacd_created_time DATETIME2(6), cacd_dw_created_time DATETIME2(6), cacd_updated_time DATETIME2(6), cacd_dw_updated_time DATETIME2(6), cacd_status INT ); 

CREATE TABLE ${schema}.staging_practice_session ( practice_session_staging_id BIGINT, practice_session_created_time DATETIME2(6), practice_session_dw_created_time DATETIME2(6), practice_session_date_dw_id INT, practice_session_id Varchar(36), lo_uuid Varchar(36), student_uuid Varchar(36), subject_uuid Varchar(36), grade_uuid Varchar(36), tenant_uuid Varchar(36), school_uuid Varchar(36), section_uuid Varchar(36), practice_session_sa_score DECIMAL(10,4), practice_session_item_lo_uuid Varchar(36) , practice_session_item_step_id Varchar(36) , practice_session_item_content_title Varchar(100) , practice_session_item_content_lesson_type Varchar(50) , practice_session_item_content_location Varchar(200) , practice_session_score DECIMAL(10,4), practice_session_event_type INT, practice_session_is_start BIT , practice_session_is_start_event_processed BIT , practice_session_outside_of_school BIT, practice_session_stars INT, academic_year_uuid Varchar(256), practice_session_instructional_plan_id Varchar(36), practice_session_learning_path_id Varchar(36), class_uuid Varchar(36), practice_session_item_content_uuid Varchar(36) , practice_session_material_id Varchar(36), practice_session_material_type Varchar(20) ) ;

CREATE TABLE ${schema}.rel_course_grade_association ( cg_dw_id BIGINT, cg_course_id Varchar(36), cg_grade_id INT, cg_status INT, cg_created_time DATETIME2(6), cg_dw_created_time DATETIME2(6), cg_updated_time DATETIME2(6), cg_dw_updated_time DATETIME2(6) ); 

CREATE TABLE ${schema}.staging_ktgskipped ( ktgskipped_staging_id BIGINT, ktgskipped_created_time DATETIME2(6), ktgskipped_dw_created_time DATETIME2(6), ktgskipped_date_dw_id BIGINT, tenant_uuid Varchar(36), student_uuid Varchar(36) , subject_uuid Varchar(36), school_uuid Varchar(36), grade_uuid Varchar(36), section_uuid Varchar(36), lo_uuid Varchar(36), academic_year_uuid Varchar(36), ktgskipped_num_key_terms SMALLINT, ktgskipped_kt_collection_id BIGINT, ktgskipped_trimester_id Varchar(256), ktgskipped_trimester_order SMALLINT, ktgskipped_type Varchar(200), ktgskipped_min_question SMALLINT, ktgskipped_max_question SMALLINT, ktgskipped_question_type Varchar(1000), ktgskipped_question_time_allotted INT, ktgskipped_instructional_plan_id Varchar(36), ktgskipped_learning_path_id Varchar(36), class_uuid Varchar(36), ktgskipped_material_id Varchar(36), ktgskipped_material_type Varchar(20) ); 

CREATE TABLE ${schema}.rel_course_content_repository_association ( ccr_dw_id BIGINT, ccr_course_id Varchar(36), ccr_repository_id Varchar(36), ccr_status INT, ccr_created_time DATETIME2(6), ccr_updated_time DATETIME2(6), ccr_deleted_time DATETIME2(6), ccr_dw_created_time DATETIME2(6), ccr_dw_updated_time DATETIME2(6), ccr_course_type Varchar(50), ccr_attach_status INT ); 

CREATE TABLE ${schema}.staging_assignment_submission ( assignment_submission_staging_id BIGINT, assignment_submission_id Varchar(36), assignment_submission_assignment_id Varchar(36), assignment_submission_referrer_id Varchar(36), assignment_submission_type Varchar(100), assignment_submission_updated_on DATETIME2(6), assignment_submission_returned_on DATETIME2(6), assignment_submission_submitted_on DATETIME2(6), assignment_submission_graded_on DATETIME2(6), assignment_submission_evaluated_on DATETIME2(6), assignment_submission_status Varchar(20), assignment_submission_student_attachment_file_name Varchar(200), assignment_submission_student_attachment_path Varchar(200), assignment_submission_teacher_attachment_path Varchar(200), assignment_submission_teacher_attachment_file_name Varchar(200), assignment_submission_teacher_score FLOAT(53), assignment_submission_date_dw_id Varchar(36), assignment_submission_created_time DATETIME2(6), assignment_submission_dw_created_time DATETIME2(6), assignment_submission_has_teacher_comment BIT, assignment_submission_has_student_comment BIT, assignment_submission_assignment_instance_id Varchar(36), assignment_submission_student_id Varchar(36), assignment_submission_teacher_id Varchar(36), assignment_submission_tenant_id Varchar(36), eventdate DATE, assignment_submission_resubmission_count INT ); 

CREATE TABLE ${schema}.staging_tutor_analogous ( fta_dw_id BIGINT, fta_created_time DATETIME2(6), fta_dw_created_time DATETIME2(6), fta_date_dw_id BIGINT, fta_user_id Varchar(36), fta_tenant_id Varchar(36), fta_message_id Varchar(36), fta_session_id Varchar(36), fta_conversation_id Varchar(36) ); 

CREATE TABLE ${schema}.staging_user_heartbeat_hourly_aggregated ( fuhha_staging_id BIGINT, fuhha_created_time DATETIME2(6), fuhha_dw_created_time DATETIME2(6), fuhha_date_dw_id BIGINT, fuhha_role Varchar(36), fuhha_channel Varchar(36), fuhha_activity_date_hour DATETIME2(6), fuhha_tenant_id Varchar(36), fuhha_user_id Varchar(36), fuhha_dw_updated_time DATETIME2(6), fuhha_school_id Varchar(36) ) ;

CREATE TABLE ${schema}.rel_assignment ( rel_assignment_id BIGINT, assignment_created_time DATETIME2(6), assignment_updated_time DATETIME2(6), assignment_deleted_time DATETIME2(6), assignment_dw_created_time DATETIME2(6), assignment_dw_updated_time DATETIME2(6), assignment_id Varchar(36), assignment_title Varchar(100), assignment_description Varchar(250), assignment_max_score DECIMAL(10,4), assignment_attachment_file_id Varchar(100), assignment_attachment_file_name Varchar(100), assignment_attachment_path Varchar(200), assignment_allow_submission BIT, assignment_language Varchar(36), assignment_status INT, assignment_is_gradeable BIT, assignment_assignment_status Varchar(36), assignment_created_by Varchar(36), assignment_updated_by Varchar(36), assignment_published_on DATETIME2(6), assignment_attachment_required BIT, assignment_comment_required BIT, assignment_type Varchar(36), assignment_metadata_author Varchar(36), assignment_metadata_is_sa BIT, assignment_metadata_authored_date Varchar(36), assignment_metadata_language Varchar(36), assignment_metadata_format_type Varchar(36), assignment_metadata_lexile_level Varchar(36), assignment_metadata_difficulty_level Varchar(36), assignment_metadata_resource_type Varchar(36), assignment_metadata_knowledge_dimensions Varchar(36), assignment_school_id Varchar(36), assignment_tenant_id Varchar(36) ); 

CREATE TABLE ${schema}.staging_pathway_teacher_activity ( fpta_dw_id BIGINT, fpta_created_time DATETIME2(6), fpta_dw_created_time DATETIME2(6), fpta_date_dw_id BIGINT, fpta_student_id Varchar(36), fpta_level_id Varchar(36), fpta_pathway_id Varchar(36), fpta_tenant_id Varchar(36), fpta_action_name Varchar(255), fpta_class_id Varchar(36), fpta_teacher_id Varchar(36), fpta_activity_id Varchar(36), fpta_action_time DATETIME2(6), fpta_activity_type INT, fpta_start_date DATE, fpta_end_date DATE, fpta_activity_progress_status Varchar(30), fpta_activity_type_value Varchar(50), fpta_is_added_as_resource BIT  ); 

CREATE TABLE ${schema}.staging_tutor_simplification ( fts_dw_id BIGINT, fts_created_time DATETIME2(6), fts_dw_created_time DATETIME2(6), fts_date_dw_id BIGINT, fts_user_id Varchar(36), fts_tenant_id Varchar(36), fts_message_id Varchar(36), fts_session_id Varchar(36), fts_conversation_id Varchar(36) ); 

CREATE TABLE ${schema}.staging_star_awarded ( fsa_staging_id BIGINT, fsa_created_time DATETIME2(6), fsa_dw_created_time DATETIME2(6), fsa_date_dw_id BIGINT, fsa_id Varchar(36), award_category_uuid Varchar(36), student_uuid Varchar(36), tenant_uuid Varchar(36), school_uuid Varchar(36), subject_uuid Varchar(36), teacher_uuid Varchar(36), grade_uuid Varchar(36), fsa_award_comments BIT, academic_year_uuid Varchar(256), class_uuid Varchar(36), fsa_stars INT ) ;

CREATE TABLE ${schema}.temp_practice_session ( practice_session_staging_id BIGINT, practice_session_created_time DATETIME2(6), practice_session_dw_created_time DATETIME2(6), practice_session_date_dw_id INT, practice_session_id Varchar(36), lo_uuid Varchar(36), student_uuid Varchar(36), subject_uuid Varchar(36), grade_uuid Varchar(36), tenant_uuid Varchar(36), school_uuid Varchar(36), class_uuid Varchar(36), skill_uuid Varchar(36), practice_session_sa_score BIGINT, practice_session_item_lo_uuid Varchar(36), practice_session_item_skill_uuid Varchar(36), practice_session_item_content_uuid Varchar(36), practice_session_item_content_title Varchar(100), practice_session_item_content_lesson_type Varchar(50), practice_session_item_content_location Varchar(200), practice_session_score BIGINT, practice_session_event_type INT, practice_session_is_start BIT, practice_session_is_start_event_processed BIT ); 

CREATE TABLE ${schema}.staging_practice ( practice_staging_id BIGINT, practice_created_time DATETIME2(6), practice_dw_created_time DATETIME2(6), practice_date_dw_id INT, practice_id Varchar(36), lo_uuid Varchar(36), student_uuid Varchar(36), subject_uuid Varchar(36), grade_uuid Varchar(36), tenant_uuid Varchar(36), school_uuid Varchar(36), section_uuid Varchar(36), skill_uuid Varchar(36), practice_sa_score DECIMAL(10,4), item_lo_uuid Varchar(36), item_skill_uuid Varchar(36), practice_item_step_id Varchar(36), practice_item_content_title Varchar(100), practice_item_content_lesson_type Varchar(50), practice_item_content_location Varchar(200), academic_year_uuid Varchar(256), practice_instructional_plan_id Varchar(36), practice_learning_path_id Varchar(36), class_uuid Varchar(36), practice_material_id Varchar(36), practice_material_type Varchar(20), section_uuid_new Varchar(144) ); 

CREATE TABLE ${schema}.rel_content_repository_material_association_a ( rel_crma_dw_id BIGINT , crma_content_repository_id Varchar(36), crma_material_id Varchar(36), crma_status INT, crma_type INT, crma_attach_status INT, crma_created_time DATETIME2(6), crma_dw_created_time DATETIME2(6), crma_updated_time DATETIME2(6), crma_dw_updated_time DATETIME2(6) ) ;

CREATE TABLE ${schema}.staging_inc_game ( inc_game_staging_id BIGINT, inc_game_id Varchar(36), inc_game_event_type INT, inc_game_created_time DATETIME2(6), inc_game_dw_created_time DATETIME2(6), inc_game_date_dw_id BIGINT, tenant_uuid Varchar(36), school_uuid Varchar(36), section_uuid Varchar(36), lo_uuid Varchar(36), inc_game_title Varchar(256), teacher_uuid Varchar(36), subject_uuid Varchar(36), grade_uuid Varchar(36), learning_path_uuid Varchar(36), inc_game_num_questions INT, inc_game_instructional_plan_id Varchar(36), class_uuid Varchar(36), inc_game_is_assessment BIT , inc_game_lesson_component_id Varchar(36) ); 

CREATE TABLE ${schema}.rel_guardian ( rel_guardian_dw_id BIGINT, guardian_created_time DATETIME2(6), guardian_updated_time DATETIME2(6), guardian_deleted_time DATETIME2(6), guardian_dw_created_time DATETIME2(6), guardian_dw_updated_time DATETIME2(6), guardian_active_until DATETIME2(6), guardian_status INT, guardian_id Varchar(36), student_id Varchar(36) , guardian_invitation_status INT ) ;

CREATE TABLE ${schema}.staging_tutor_session ( fts_dw_id BIGINT, fts_created_time DATETIME2(6), fts_dw_created_time DATETIME2(6), fts_date_dw_id BIGINT, fts_session_id Varchar(36), fts_tenant_id Varchar(36), fts_school_id Varchar(36), fts_user_id Varchar(36), fts_grade_id Varchar(36), fts_context_id Varchar(36), fts_role Varchar(20), fts_grade INT, fts_subject_id Varchar(36), fts_subject Varchar(20), fts_language Varchar(20), fts_session_state Varchar(20), fts_activity_id Varchar(36), fts_activity_status Varchar(20), fts_material_id Varchar(36), fts_material_type Varchar(20), fts_level_id Varchar(36), fts_outcome_id Varchar(36), fts_session_message_limit_reached BIT, fts_learning_session_id Varchar(36) ) ;

CREATE TABLE ${schema}.rel_question ( rel_question_id BIGINT, question_created_time DATETIME2(6), question_updated_time DATETIME2(6), question_deleted_time DATETIME2(6), question_dw_created_time DATETIME2(6), question_dw_updated_time DATETIME2(6), question_status INT, question_id Varchar(36), question_code Varchar(128), question_triggered_by Varchar(50), question_language Varchar(50), question_type Varchar(50), question_max_score FLOAT(53), question_version INT, question_stage Varchar(50), question_variant Varchar(5), question_active_until DATETIME2(6), question_format_type Varchar(30), question_resource_type Varchar(10), question_summative_assessment BIT, question_difficulty_level Varchar(50), question_knowledge_dimensions Varchar(128), question_lexile_level Varchar(36), question_author Varchar(70), question_authored_date DATETIME2(6), question_skill_id Varchar(36), question_cefr_level Varchar(50), question_proficiency Varchar(50) ) ;

CREATE TABLE ${schema}.staging_adt_next_question ( fanq_staging_id BIGINT, fanq_created_time DATETIME2(6), fanq_dw_created_time DATETIME2(6), fanq_date_dw_id BIGINT , fanq_id Varchar(36), fle_ls_uuid Varchar(36), student_uuid Varchar(36), fanq_question_pool_id Varchar(36), tenant_uuid Varchar(36), fanq_response BIT, fanq_proficiency FLOAT(53), fanq_next_question_id Varchar(4000), fanq_time_spent FLOAT(53), fanq_current_question_id Varchar(1000), fanq_intest_progress FLOAT(53), fanq_status INT, fanq_curriculum_subject_id INT, fanq_curriculum_subject_name Varchar(36), fanq_language Varchar(50), fanq_standard_error FLOAT(53), fanq_attempt INT, school_uuid Varchar(36), fanq_grade INT, fanq_grade_id Varchar(36), fanq_academic_year INT, fanq_academic_year_id Varchar(36), fanq_academic_term SMALLINT, fanq_class_subject_name Varchar(64), fanq_skill Varchar(20) ) ;

CREATE TABLE ${schema}.staging_teacher_activities ( fta_staging_id BIGINT, fta_created_time DATETIME2(6), fta_dw_created_time DATETIME2(6), fta_actor_object_type Varchar(100), fta_actor_account_homepage Varchar(100), fta_verb_id Varchar(100), fta_verb_display Varchar(100), fta_object_id Varchar(2000), fta_object_type Varchar(100), fta_object_definition_type Varchar(100), fta_object_definition_name Varchar(2000), fta_context_category Varchar(100), fta_outside_of_school BIT, fta_event_type Varchar(100), fta_prev_event_type Varchar(100), fta_next_event_type Varchar(100), fta_date_dw_id BIGINT, tenant_uuid Varchar(36), school_uuid Varchar(36), grade_uuid Varchar(36), section_uuid Varchar(36), subject_uuid Varchar(36), teacher_uuid Varchar(36) , fta_start_time DATETIME2(6), fta_end_time DATETIME2(6), fta_timestamp_local Varchar(100), fta_time_spent FLOAT(53) ); 

CREATE TABLE ${schema}.staging_student_slide_progress ( dw_id BIGINT, event_type Varchar(100), created_time DATETIME2(6), dw_created_time DATETIME2(6), _trace_id Varchar(36), tenant_id Varchar(36), date_dw_id BIGINT, experience_id Varchar(36), learning_session_id Varchar(36), content_section_id Varchar(36), slide_id Varchar(36), widget_id Varchar(50), status Varchar(20), active_time INT, idle_time INT, total_time_spent INT, result Varchar(20), attempt INT, student_id Varchar(36) , school_id Varchar(36), grade_id Varchar(36), student_section_id Varchar(36), class_id Varchar(36), activity_id Varchar(36), academic_year_tag Varchar(20), material_id Varchar(36), material_type Varchar(20), ccl_content_id BIGINT, channel Varchar(50), _ingestion_type Varchar(10) ); 

CREATE TABLE ${schema}.staging_student_queries_copy_jyo ( dw_id BIGINT, created_time DATETIME2(6), dw_created_time DATETIME2(6), date_dw_id BIGINT, _trace_id Varchar(36), event_type Varchar(36), message_id Varchar(36), query_id Varchar(36), tenant_id Varchar(36), school_id Varchar(36), grade_id Varchar(36), class_id Varchar(36), section_id Varchar(36), teacher_id Varchar(36), academic_year_id Varchar(36), student_id Varchar(36), mlo_id Varchar(36), activity_id Varchar(36), activity_title Varchar(100), activity_type Varchar(100), can_student_reply BIT, with_audio BIT, with_text BIT, material_type Varchar(100), crumb_title Varchar(100), gen_subject Varchar(100), lang_code Varchar(100), is_follow_up BIT, has_screenshot BIT ); 

CREATE TABLE ${schema}.rel_pacing_guide ( pacing_id Varchar(36), pacing_dw_id BIGINT, pacing_course_id Varchar(36), pacing_class_id Varchar(36), pacing_academic_calendar_id Varchar(36), pacing_academic_year_id Varchar(36), pacing_activity_id Varchar(36), pacing_tenant_id Varchar(36), pacing_status INT, pacing_activity_order INT, pacing_ip_id Varchar(36), pacing_period_start_date DATE, pacing_period_label Varchar(25), pacing_period_id Varchar(36), pacing_period_end_date DATE, pacing_interval_id Varchar(36), pacing_interval_start_date DATE, pacing_interval_label Varchar(240), pacing_interval_end_date DATE, pacing_created_time DATETIME2(6), pacing_dw_created_time DATETIME2(6), pacing_updated_time DATETIME2(6), pacing_dw_updated_time DATETIME2(6), pacing_interval_type Varchar(20) ); 

CREATE TABLE ${schema}.rel_academic_calendar ( academic_calendar_dw_id BIGINT, academic_calendar_created_time DATETIME2(6), academic_calendar_updated_time DATETIME2(6), academic_calendar_deleted_time DATETIME2(6), academic_calendar_dw_created_time DATETIME2(6), academic_calendar_dw_updated_time DATETIME2(6), academic_calendar_status INT, academic_calendar_tenant_id Varchar(36), academic_calendar_title Varchar(50), academic_calendar_id Varchar(36), academic_calendar_school_id Varchar(36), academic_calendar_is_default BIT, academic_calendar_type Varchar(30), academic_calendar_organization Varchar(50), academic_calendar_academic_year_id Varchar(36), academic_calendar_created_by_id Varchar(36), academic_calendar_updated_by_id Varchar(36), academic_calendar_organization_code Varchar(20) ); 

CREATE TABLE ${schema}.rel_academic_year ( academic_year_delta_dw_id BIGINT, academic_year_created_time DATETIME2(6), academic_year_updated_time DATETIME2(6), academic_year_deleted_time DATETIME2(6), academic_year_dw_created_time DATETIME2(6), academic_year_dw_updated_time DATETIME2(6), academic_year_status SMALLINT, academic_year_id Varchar(36), academic_year_organization_code Varchar(50), academic_year_school_id Varchar(36), academic_year_state Varchar(50), academic_year_start_date DATE, academic_year_end_date DATE, academic_year_created_by Varchar(36), academic_year_updated_by Varchar(36), academic_year_is_roll_over_completed BIT , academic_year_type Varchar(36) ); 

CREATE TABLE ${schema}.staging_pathway_target_progress ( fptp_dw_id BIGINT, fptp_id Varchar(36), fptp_created_time DATETIME2(6), fptp_dw_created_time DATETIME2(6), fptp_date_dw_id BIGINT, fptp_student_target_id Varchar(36), fptp_target_id Varchar(36), fptp_student_id Varchar(36), fptp_tenant_id Varchar(36), fptp_school_id Varchar(36), fptp_grade_id Varchar(36), fptp_class_id Varchar(36), fptp_teacher_id Varchar(36), fptp_pathway_id Varchar(36), fptp_target_state Varchar(20), fptp_recommended_target_level INT, fptp_finalized_target_level INT, fptp_levels_completed INT, fptp_earned_stars INT ); 

CREATE TABLE ${schema}.rel_teacher_feedback_thread ( rel_tft_id BIGINT, tft_status SMALLINT, tft_created_time DATETIME2(6), tft_dw_created_time DATETIME2(6), tft_deleted_time DATETIME2(6), tft_updated_time DATETIME2(6), tft_dw_updated_time DATETIME2(6), tft_thread_id Varchar(36), tft_actor_type SMALLINT, tft_guardian_id Varchar(36), tft_message_id Varchar(36), tft_response_enabled BIT, tft_feedback_type SMALLINT, tft_teacher_id Varchar(36), tft_student_id Varchar(36), tft_class_id Varchar(36), tft_is_read BIT, tft_event_subject SMALLINT, tft_is_first_of_thread BIT ); 

CREATE TABLE ${schema}.staging_inc_game_session ( inc_game_session_staging_id BIGINT, inc_game_session_id Varchar(36), inc_game_session_created_time DATETIME2(6), inc_game_session_dw_created_time DATETIME2(6), inc_game_session_date_dw_id BIGINT, tenant_uuid Varchar(36), game_uuid Varchar(36), inc_game_session_title Varchar(256), inc_game_session_num_players INT, inc_game_session_num_joined_players INT, inc_game_session_started_by Varchar(36), inc_game_session_status INT, inc_game_session_is_start BIT , inc_game_session_is_start_event_processed BIT , inc_game_session_is_assessment BIT  ); 

CREATE TABLE ${schema}.staging_learning_score_breakdown ( fle_scbd_dw_id BIGINT, fle_scbd_created_time DATETIME2(6), fle_scbd_dw_created_time DATETIME2(6), fle_scbd_date_dw_id BIGINT, fle_scbd_fle_exp_id Varchar(36), fle_scbd_fle_ls_id Varchar(36), fle_scbd_question_id Varchar(36), fle_scbd_code Varchar(50), fle_scbd_time_spent FLOAT(53), fle_scbd_hints_used BIT, fle_scbd_max_score FLOAT(53), fle_scbd_score FLOAT(53), fle_scbd_lo_id Varchar(36), fle_scbd_type Varchar(250), fle_scbd_version INT, fle_scbd_is_attended BIT ) ;

CREATE TABLE ${schema}.staging_badge_awarded ( fba_dw_id BIGINT , fba_id Varchar(36), fba_created_time DATETIME2(6), fba_dw_created_time DATETIME2(6), fba_date_dw_id BIGINT, fba_student_id Varchar(36), fba_tenant_id Varchar(36), fba_badge_type Varchar(100), fba_badge_type_id Varchar(36), fba_tier Varchar(50), fba_academic_year_id Varchar(36), fba_section_id Varchar(36), fba_grade_id Varchar(36), fba_school_id Varchar(36) ) ;

CREATE TABLE ${schema}.staging_inc_game_outcome ( inc_game_outcome_staging_id BIGINT, inc_game_outcome_id Varchar(36), inc_game_outcome_created_time DATETIME2(6), inc_game_outcome_dw_created_time DATETIME2(6), inc_game_outcome_date_dw_id BIGINT, tenant_uuid Varchar(36), session_uuid Varchar(36), game_uuid Varchar(36), player_uuid Varchar(36), lo_uuid Varchar(36), inc_game_outcome_score FLOAT(53), inc_game_outcome_status INT, inc_game_outcome_is_assessment BIT  ); 

CREATE TABLE ${schema}.rel_course_resource_activity_grade_association ( craga_dw_id BIGINT, craga_created_time DATETIME2(6), craga_updated_time DATETIME2(6), craga_deleted_time DATETIME2(6), craga_dw_created_time DATETIME2(6), craga_dw_updated_time DATETIME2(6), craga_dw_deleted_time DATETIME2(6), craga_status INT, craga_course_id Varchar(36), craga_activity_id Varchar(36), craga_grade_id Varchar(5) ) ;

CREATE TABLE ${schema}.rel_activity_section_association ( dw_id BIGINT, event_type Varchar(100), _trace_id Varchar(36), tenant_id Varchar(36), id Varchar(36), created_time DATETIME2(6), dw_created_time DATETIME2(6), status SMALLINT, active_until DATETIME2(6), section_id Varchar(36), activity_id Varchar(36), template_component_uuid Varchar(36), content_id BIGINT, _ingestion_type Varchar(10) ); 

CREATE TABLE ${schema}.staging_level_completed ( flc_dw_id BIGINT, flc_created_time DATETIME2(6), flc_dw_created_time DATETIME2(6), flc_date_dw_id BIGINT, flc_completed_on DATETIME2(6), flc_tenant_id Varchar(36), flc_student_id Varchar(36), flc_class_id Varchar(36), flc_pathway_id Varchar(36), flc_level_id Varchar(36), flc_total_stars INT, flc_academic_year Varchar(50), flc_score INT ) ;

CREATE TABLE ${schema}.rel_staff_user ( rel_staff_user_dw_id BIGINT, staff_user_event_type Varchar(50) , staff_user_created_time DATETIME2(6), staff_user_dw_created_time DATETIME2(6), staff_user_active_until DATETIME2(6), staff_user_status INT, staff_user_id Varchar(36), staff_user_onboarded BIT, staff_user_expirable BIT , staff_user_exclude_from_report BIT , staff_user_avatar Varchar(100), staff_user_enabled BIT ); 

CREATE TABLE ${schema}.rel_team_student_association ( rel_team_student_association_id BIGINT, team_student_association_created_time DATETIME2(6), team_student_association_updated_time DATETIME2(6), team_student_association_dw_created_time DATETIME2(6), team_student_association_dw_updated_time DATETIME2(6), team_student_association_status SMALLINT, team_student_association_active_until DATETIME2(6), team_uuid Varchar(36), student_uuid Varchar(36) ); 

CREATE TABLE ${schema}.staging_announcement ( fa_dw_id BIGINT, fa_created_time DATETIME2(6), fa_dw_created_time DATETIME2(6), fa_status INT, fa_tenant_id Varchar(36), fa_id Varchar(36), fa_admin_id Varchar(36), fa_role_id Varchar(36), fa_recipient_type INT, fa_recipient_type_description Varchar(50), fa_recipient_id Varchar(36), fa_has_attachment BIT, fa_type INT ); 

CREATE TABLE ${schema}.rel_staff_user_school_role_association ( susra_dw_id BIGINT, susra_event_type Varchar(50), susra_staff_id Varchar(36), susra_school_id Varchar(36), susra_role_name Varchar(50), susra_role_uuid Varchar(36), susra_organization Varchar(50), susra_status INT, susra_created_time DATETIME2(6), susra_dw_created_time DATETIME2(6), susra_active_until DATETIME2(6) ); 

CREATE TABLE ${schema}.rel_course_curriculum_association ( cc_dw_id BIGINT, cc_course_id Varchar(36), cc_curr_id BIGINT, cc_curr_grade_id BIGINT, cc_curr_subject_id BIGINT , cc_status INT, cc_created_time DATETIME2(6), cc_updated_time DATETIME2(6), cc_deleted_time DATETIME2(6), cc_dw_created_time DATETIME2(6), cc_dw_updated_time DATETIME2(6) ); 

CREATE TABLE ${schema}.rel_tag ( tag_dw_id BIGINT, tag_created_time DATETIME2(6), tag_updated_time DATETIME2(6), tag_dw_created_time DATETIME2(6), tag_dw_updated_time DATETIME2(6), tag_id Varchar(36), tag_name Varchar(1024), tag_status INT, tag_type Varchar(36), tag_association_id Varchar(36), tag_association_type INT, tag_association_attach_status INT ); 

CREATE TABLE ${schema}.staging_tutor_translation ( ftt_dw_id BIGINT, ftt_created_time DATETIME2(6), ftt_dw_created_time DATETIME2(6), ftt_date_dw_id BIGINT, ftt_user_id Varchar(36), ftt_tenant_id Varchar(36), ftt_message_id Varchar(36), ftt_session_id Varchar(36), ftt_conversation_id Varchar(36), ftt_translation_language Varchar(50) ); 

CREATE TABLE ${schema}.staging_learning_experience ( fle_staging_id BIGINT, fle_created_time DATETIME2(6), fle_dw_created_time DATETIME2(6), fle_date_dw_id BIGINT, fle_exp_id Varchar(36), fle_ls_id Varchar(36), fle_step_id Varchar(36), lo_uuid Varchar(36), student_uuid Varchar(36) , subject_uuid Varchar(36), grade_uuid Varchar(36), curr_subject_uuid Varchar(36), curr_grade_uuid Varchar(36), curr_uuid Varchar(36), tenant_uuid Varchar(36), school_uuid Varchar(36), section_uuid Varchar(36), lp_uuid Varchar(36), fle_start_time DATETIME2(6), fle_end_time DATETIME2(6), fle_total_time FLOAT(53), fle_score INT, fle_star_earned INT, fle_lesson_type Varchar(50), fle_is_retry BIT, fle_outside_of_school BIT, fle_attempt INT, fle_exp_ls_flag BIT, fle_academic_period_order Varchar(20), academic_year_uuid Varchar(256), fle_content_academic_year Varchar(36), fle_time_spent_app INT, fle_instructional_plan_id Varchar(36), class_uuid Varchar(36), fle_lesson_category Varchar(40), fle_adt_level Varchar(20), fle_abbreviation Varchar(100), fle_activity_template_id Varchar(100), fle_activity_type Varchar(100), fle_activity_component_type Varchar(100), fle_exit_ticket BIT, fle_main_component BIT, fle_completion_node BIT, fle_total_score DECIMAL(10,4), fle_is_activity_completed BIT, fle_material_id Varchar(36), fle_material_type Varchar(20), fle_state SMALLINT, fle_total_stars SMALLINT, fle_open_path_enabled BIT , fle_source Varchar(10), fle_teaching_period_id Varchar(36), fle_academic_year Varchar(10), fle_assessment_id Varchar(36), fle_is_gamified BIT , fle_is_additional_resource BIT , fle_bonus_stars INT , fle_bonus_stars_scheme Varchar(40)  ) ;

CREATE TABLE ${schema}.staging_student_activities ( fsta_staging_id BIGINT, fsta_created_time DATETIME2(6), fsta_dw_created_time DATETIME2(6), fsta_actor_object_type Varchar(100), fsta_actor_account_homepage Varchar(100), fsta_verb_display Varchar(100), fsta_verb_id Varchar(100), fsta_object_id Varchar(2000), fsta_object_type Varchar(100), fsta_object_definition_type Varchar(100), fsta_object_definition_name Varchar(2000), fsta_from_time DECIMAL(5,0), fsta_to_time DECIMAL(5,0), fsta_outside_of_school BIT, fsta_event_type Varchar(100), fsta_prev_event_type Varchar(100), fsta_next_event_type Varchar(100), fsta_date_dw_id BIGINT, fsta_attempt SMALLINT, fsta_score_scaled DECIMAL(6,2), fsta_score_max DECIMAL(6,2), fsta_score_min DECIMAL(6,2), fsta_lesson_position SMALLINT, fsta_exp_id Varchar(36), fsta_ls_id Varchar(36), tenant_uuid Varchar(36), school_uuid Varchar(36), grade_uuid Varchar(36), section_uuid Varchar(36), subject_uuid Varchar(36), student_uuid Varchar(36) , academic_year_uuid Varchar(36), fsta_timestamp_local Varchar(100), fsta_start_time DATETIME2(6), fsta_end_time DATETIME2(6), fsta_time_spent FLOAT(53), fsta_score_raw DECIMAL(8,2), fsta_is_completion_node BIT, fsta_is_flexible_lesson BIT, fsta_academic_calendar_id Varchar(36), fsta_teaching_period_id Varchar(36), fsta_teaching_period_title Varchar(50) ); 

CREATE TABLE ${schema}.test_table_stage ( id BIGINT );
