-- SOURCE: Amazon Redshift docs
-- URL: https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_examples.html
-- DATABASE: Redshift
-- OBJECT TYPE: CREATE TABLE
-- FEATURE: DEFAULT IDENTITY
-- DESCRIPTION: Redshift default identity example with override-able identity column.
CREATE TABLE t1(
  hist_id BIGINT IDENTITY NOT NULL,
  base_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  business_key varchar(10),
  some_field varchar(10)
);
