-- SOURCE: dbeaver/dbeaver issue example
-- URL: https://github.com/dbeaver/dbeaver/issues/13544
-- DATABASE: Redshift
-- OBJECT TYPE: CREATE TABLE
-- FEATURE: MULTI-TYPE COVERAGE + ENCODE + DISTSTYLE AUTO
-- DESCRIPTION: Real-world table covering a broad set of Redshift scalar types.
CREATE TABLE IF NOT EXISTS test_all_types
(
  c1 SMALLINT ENCODE az64,
  c2 INTEGER ENCODE az64,
  c3 BIGINT ENCODE az64,
  c4 NUMERIC(18,0) ENCODE az64,
  c5 REAL ENCODE RAW,
  c6 DOUBLE PRECISION ENCODE RAW,
  c7 BOOLEAN ENCODE RAW,
  c8 CHAR(1) ENCODE lzo,
  c9 VARCHAR(256) ENCODE lzo,
  c10 DATE ENCODE az64,
  c11 TIMESTAMP WITHOUT TIME ZONE ENCODE az64,
  c12 TIMESTAMP WITH TIME ZONE ENCODE az64,
  c15 TIME WITHOUT TIME ZONE ENCODE az64,
  c16 TIME WITH TIME ZONE ENCODE az64,
  "-c10" VARCHAR(10) ENCODE lzo
)
DISTSTYLE AUTO;
