-- =============================================================================
-- KITCHEN SINK: Oracle Database
-- Exercises GENERATED ALWAYS AS IDENTITY, all Oracle types (VARCHAR2, NUMBER,
-- DATE, TIMESTAMP), NVL/NVL2/DECODE, PARTITION BY RANGE/LIST/HASH,
-- GLOBAL TEMPORARY, CREATE VIEW, CREATE MATERIALIZED VIEW,
-- CREATE PROCEDURE (PL/SQL), CREATE FUNCTION.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Dimension table — GENERATED AS IDENTITY, all Oracle types, RANGE PARTITION
-- ---------------------------------------------------------------------------
CREATE TABLE orders.dim_customers (
    customer_id         NUMBER          GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    customer_uuid       VARCHAR2(36)    NOT NULL,
    full_name           VARCHAR2(255)   NOT NULL,
    email               VARCHAR2(320)   NOT NULL,
    tier                VARCHAR2(20)    DEFAULT 'standard' NOT NULL,
    score               NUMBER(5, 2)    DEFAULT 0,
    is_active           NUMBER(1)       DEFAULT 1 NOT NULL,
    signup_date         DATE            NOT NULL,
    last_login          TIMESTAMP,
    last_login_tz       TIMESTAMP WITH TIME ZONE,
    region_code         CHAR(3),
    lifetime_value      BINARY_FLOAT,
    raw_notes           CLOB,
    CONSTRAINT PK_dim_customers        PRIMARY KEY (customer_id),
    CONSTRAINT UQ_dim_customers_uuid   UNIQUE (customer_uuid),
    CONSTRAINT UQ_dim_customers_email  UNIQUE (email),
    CONSTRAINT CK_dim_customers_tier   CHECK (tier IN ('standard', 'premium', 'enterprise')),
    CONSTRAINT CK_dim_customers_score  CHECK (score >= 0 AND score <= 100),
    CONSTRAINT FK_dim_customers_self   FOREIGN KEY (customer_id) REFERENCES orders.dim_customers (customer_id)
)
PARTITION BY RANGE (signup_date) (
    PARTITION p_2023 VALUES LESS THAN (DATE '2024-01-01'),
    PARTITION p_2024 VALUES LESS THAN (DATE '2025-01-01'),
    PARTITION p_max  VALUES LESS THAN (MAXVALUE)
);

-- ---------------------------------------------------------------------------
-- 2. Fact table — BY DEFAULT ON NULL IDENTITY, all numeric types, LIST PARTITION
-- ---------------------------------------------------------------------------
CREATE TABLE orders.fact_orders (
    order_id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id     NUMBER(10)      NOT NULL,
    product_id      NUMBER(10)      NOT NULL,
    order_amount    NUMBER(18, 4)   DEFAULT 0 NOT NULL,
    discount_pct    BINARY_FLOAT    DEFAULT 0,
    tax_amount      NUMBER(10, 2)   DEFAULT 0,
    quantity        NUMBER(5)       DEFAULT 1,
    is_gift         NUMBER(1)       DEFAULT 0,
    notes           VARCHAR2(1000)  DEFAULT 'N/A',
    order_code      CHAR(10),
    order_date      DATE            NOT NULL,
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_fact_orders          PRIMARY KEY (order_id),
    CONSTRAINT FK_fact_orders_customer FOREIGN KEY (customer_id)
                                       REFERENCES orders.dim_customers (customer_id),
    CONSTRAINT UQ_fact_orders_code     UNIQUE (order_code),
    CONSTRAINT CK_fact_orders_qty      CHECK (quantity > 0)
)
PARTITION BY LIST (is_gift) (
    PARTITION p_regular VALUES (0),
    PARTITION p_gift    VALUES (1)
);

-- ---------------------------------------------------------------------------
-- 3. Global temporary table (session-scoped)
-- ---------------------------------------------------------------------------
CREATE GLOBAL TEMPORARY TABLE orders.tmp_order_staging (
    order_id        NUMBER,
    customer_id     NUMBER,
    order_amount    NUMBER(18, 4),
    loaded_at       TIMESTAMP DEFAULT SYSTIMESTAMP
)
ON COMMIT DELETE ROWS;

-- ---------------------------------------------------------------------------
-- 4. Simple view using NVL and DECODE
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW orders.v_active_customers AS
SELECT
    customer_id,
    full_name,
    email,
    tier,
    NVL(region_code, 'UNK')                       AS region_code,
    DECODE(is_active, 1, 'Yes', 0, 'No', 'Unknown') AS active_label,
    signup_date
FROM orders.dim_customers
WHERE is_active = 1;

-- ---------------------------------------------------------------------------
-- 5. Materialized view — REFRESH ON COMMIT, QUERY REWRITE
-- ---------------------------------------------------------------------------
CREATE MATERIALIZED VIEW orders.mv_customer_totals
BUILD IMMEDIATE
REFRESH ON COMMIT
ENABLE QUERY REWRITE AS
SELECT
    c.tier,
    TRUNC(o.order_date, 'MM')   AS order_month,
    COUNT(*)                     AS order_count,
    SUM(o.order_amount)          AS total_amount,
    AVG(o.discount_pct)          AS avg_discount
FROM orders.fact_orders   o
JOIN orders.dim_customers c ON o.customer_id = c.customer_id
GROUP BY c.tier, TRUNC(o.order_date, 'MM');

-- ---------------------------------------------------------------------------
-- 6. PL/SQL stored procedure — NVL2, DECODE, NVL, SYSDATE
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE orders.sp_update_customer_tier(
    p_customer_id   IN  NUMBER,
    p_email         IN  VARCHAR2,
    p_tier          IN  VARCHAR2,
    p_result        OUT VARCHAR2
)
AS
    v_current_tier VARCHAR2(20);
BEGIN
    SELECT tier INTO v_current_tier
    FROM orders.dim_customers
    WHERE customer_id = p_customer_id;

    UPDATE orders.dim_customers
    SET
        email      = NVL(p_email, email),
        tier       = NVL2(
                       p_tier,
                       DECODE(p_tier,
                           'gold',   'premium',
                           'silver', 'standard',
                           'bronze', 'standard',
                           p_tier
                       ),
                       v_current_tier
                     ),
        last_login = SYSDATE
    WHERE customer_id = p_customer_id;

    p_result := 'OK';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_result := 'NOT_FOUND';
END sp_update_customer_tier;

-- ---------------------------------------------------------------------------
-- 7. PL/SQL function — RETURN keyword (not RETURNS)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION orders.fn_safe_divide(
    p_numerator   NUMBER,
    p_denominator NUMBER
)
RETURN NUMBER
AS
BEGIN
    IF p_denominator = 0 THEN
        RETURN 0;
    END IF;
    RETURN p_numerator / p_denominator;
END fn_safe_divide;
