IF OBJECT_ID('${schema}.core_assignment_dm', 'U') IS NULL 
BEGIN
CREATE TABLE ${schema}.core_assignment_dm (
    assignment_dw_id BIGINT,
    assignment_title VARCHAR(300),
    assignment_max_score DECIMAL(30,4),
    assignment_language VARCHAR(256),
    assignment_is_gradeable BIT,
    assignment_attachment_required BIT,
    assignment_comment_required BIT,
    difficulty_level VARCHAR(50),
    resource_type VARCHAR(50),
    knowledge_dimensions VARCHAR(50),
    student_dw_id BIGINT,
    instructional_plan_dw_id BIGINT,
    instructional_plan_name VARCHAR(255),
    academic_year_id VARCHAR(36),
    week_dw_id BIGINT,
    week_number FLOAT,
    week_start_date DATE,
    week_end_date DATE,
    term_academic_period_order INT,
    term_start_date DATE,
    term_end_date DATE,
    lo_to_finish BIGINT,
    lo_title VARCHAR(750),
    instructional_plan_item_optional BIT,
    organisation_dw_id BIGINT,
    organisation_name VARCHAR(50),
    curr_subject_name VARCHAR(255),
    curr_grade_name VARCHAR(250),
    academic_year_start_date DATE,
    academic_year_end_date DATE,
    school_id VARCHAR(36),
    school_name VARCHAR(384),
    tenant_name VARCHAR(765),
    class_id VARCHAR(36),
    is_locked BIT,
    assignment_submission_id VARCHAR(36),
    assignment_submission_assignment_id VARCHAR(36),
    assignment_submission_type VARCHAR(100),
    assignment_submission_submitted_on DATETIME2(6),
    assignment_submission_status VARCHAR(20),
    assignment_submission_teacher_score FLOAT,
    assignment_submission_resubmission_count INT
);
END;

IF OBJECT_ID('${schema}.nce_student_login_activity_dm', 'U') IS NULL 
BEGIN
CREATE TABLE ${schema}.nce_student_login_activity_dm (
    local_date DATE,
    academic_year VARCHAR(15),
    tenant_name VARCHAR(765),
    school_dw_id BIGINT,
    school_name VARCHAR(384),
    school_city_name VARCHAR(100),
    school_organisation VARCHAR(50),
    school_latitude DECIMAL(10,6),
    school_longitude DECIMAL(10,6),
    school_label VARCHAR(30),
    grade INT,
    class VARCHAR(100),
    section VARCHAR(100),
    student_tags VARCHAR(256),
    special_needs VARCHAR(3),
    available_student_dw_id BIGINT,
    active_student_dw_id BIGINT,
    student_id VARCHAR(36),
    student_current_status INT,
    academic_year_start_date DATE,
    academic_year_end_date DATE,
    section_dw_id BIGINT,
    holiday_flag BIT,
    class_gen_subject VARCHAR(255),
    class_dw_id BIGINT
);
END;
