CREATE OR ALTER VIEW ${os_bi_coredw}.magg_student_teacher_kpi_historical_dm
AS
SELECT
    calendar_year_end_date,
    calendar_month_start_date,
    calendar_month_end_date,
    tenant_dw_id,
    tenant_name,
    content_repository_dw_id,
    content_repository_name,
    academic_year_start_date,
    academic_year_end_date,
    school_dw_id,
    school_name,
    grade_name,
    ay,
    registered_students,
    onboarded_students,
    students_logged_in,
    NULL AS registered_teachers,
    NULL AS onboarded_teachers,
    NULL AS teachers_logged_in,
    reg_school_cumsum,
    reg_student_cumsum,
    onb_school_cumsum,
    onb_student_cumsum,
    NULL AS reg_teacher_cumsum,
    NULL AS onb_teacher_cumsum,
    ay_rank,
    registered_students_cy,
    onboarded_students_cy,
    registered_students_ay,
    onboarded_students_ay,
    NULL AS registered_teachers_cy,
    NULL AS onboarded_teachers_cy,
    NULL AS registered_teachers_ay,
    NULL AS onboarded_teachers_ay,
    inserted_at,
    dense_rank,
    'student' AS record_type
FROM ${rs_bi_coredw}.magg_student_kpi_historical

UNION ALL

SELECT
    calendar_year_end_date,
    calendar_month_start_date,
    calendar_month_end_date,
    tenant_dw_id,
    tenant_name,
    content_repository_dw_id,
    content_repository_name,
    academic_year_start_date,
    academic_year_end_date,
    school_dw_id,
    school_name,
    'N/A' AS grade_name,
    ay,
    NULL AS registered_students,
    NULL AS onboarded_students,
    NULL AS students_logged_in,
    registered_teachers,
    onboarded_teachers,
    teachers_logged_in,
    NULL AS reg_school_cumsum,
    NULL AS reg_student_cumsum,
    NULL AS onb_school_cumsum,
    NULL AS onb_student_cumsum,
    reg_teacher_cumsum,
    onb_teacher_cumsum,
    NULL AS ay_rank,
    NULL AS registered_students_cy,
    NULL AS onboarded_students_cy,
    NULL AS registered_students_ay,
    NULL AS onboarded_students_ay,
    registered_teachers_cy,
    onboarded_teachers_cy,
    registered_teachers_ay,
    onboarded_teachers_ay,
    inserted_at,
    dense_rank,
    'teacher' AS record_type
FROM ${rs_bi_coredw}.magg_teacher_kpi_historical;
