CREATE TABLE "hr"."orders" (
    "order_id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "customer_id" NUMBER NOT NULL,
    "amount" NUMBER(18,2) NOT NULL,
    "status" VARCHAR2(32) DEFAULT 'pending',
    "created_at" TIMESTAMP NOT NULL
);