CREATE OR REPLACE VIEW bi_alefdw_dev.agg_student_engagement_periods_view AS
    -- Last 7 Days
    SELECT
        'LAST 7 DAYS' AS period,
       fles.tenant_name,
       fles.school_organisation,
       fles.school_name,
       fles.school_id,
       fles.school_dw_id,
       fles.school_country_name,
       fles.school_city_name,
       fles.school_label,
       fles.school_status,
       fles.grade_name,
       fles.class_gen_subject,
        COUNT(DISTINCT CASE WHEN is_last_7_days = 1 THEN fle_student_dw_id END) AS total_students,
        COUNT(CASE WHEN is_last_7_days = 1 THEN 1 END) AS total_students_days,
        SUM(CASE WHEN is_last_7_days = 1 THEN session_time ELSE 0 END) AS total_time_spent,
        SUM(CASE WHEN is_last_7_days = 1 THEN total_lessons_learned END) AS total_lessons_learned,
        SUM(CASE WHEN is_last_7_days = 1 THEN total_completed_lessons END) AS total_completed_lessons,
        SUM(CASE WHEN is_last_7_days = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score,
        SUM(CASE WHEN is_last_7_days = 1 THEN fle_score ELSE 0 END) AS total_score,
        COUNT(DISTINCT CASE WHEN is_last_7_days_pp = 1 THEN fle_student_dw_id END) AS total_students_previous_period,
        COUNT(CASE WHEN is_last_7_days_pp = 1 THEN 1 END) AS total_students_days_previous_period,
        SUM(CASE WHEN is_last_7_days_pp = 1 THEN session_time ELSE 0 END) AS total_time_spent_previous_period,
        SUM(CASE WHEN is_last_7_days_pp = 1 THEN total_lessons_learned END) AS total_lessons_learned_previous_period,
        SUM(CASE WHEN is_last_7_days_pp = 1 THEN total_completed_lessons END) AS total_completed_lessons_previous_period,
        SUM(CASE WHEN is_last_7_days_pp  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_previous_period,
        SUM(CASE WHEN is_last_7_days_pp = 1 THEN fle_score ELSE 0 END) AS total_score_previous_period,
        COUNT(DISTINCT CASE WHEN is_last_7_days_ly = 1 THEN fle_student_dw_id END) AS total_students_last_year,
        COUNT(CASE WHEN is_last_7_days_ly = 1 THEN 1 END) AS total_students_days_last_year,
        SUM(CASE WHEN is_last_7_days_ly = 1 THEN session_time ELSE 0 END) AS total_time_spent_last_year,
        SUM(CASE WHEN is_last_7_days_ly = 1 THEN total_lessons_learned END) AS total_lessons_learned_last_year,
        SUM(CASE WHEN is_last_7_days_ly = 1 THEN total_completed_lessons END) AS total_completed_lessons_last_year,
        SUM(CASE WHEN is_last_7_days_ly  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_last_year,
        SUM(CASE WHEN is_last_7_days_ly = 1 THEN fle_score ELSE 0 END) AS total_score_last_year,
        COUNT(DISTINCT CASE WHEN is_last_7_days_2ya = 1 THEN fle_student_dw_id END) AS total_students_2_years_back,
        COUNT(CASE WHEN is_last_7_days_2ya = 1 THEN 1 END) AS total_students_days_2_years_back,
        SUM(CASE WHEN is_last_7_days_2ya = 1 THEN session_time ELSE 0 END) AS total_time_spent_2_years_back,
        SUM(CASE WHEN is_last_7_days_2ya = 1 THEN total_lessons_learned END) AS total_lessons_learned_2_years_back,
        SUM(CASE WHEN is_last_7_days_2ya = 1 THEN total_completed_lessons END) AS total_completed_lessons_2_years_back,
        SUM(CASE WHEN is_last_7_days_2ya  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_2_years_back,
        SUM(CASE WHEN is_last_7_days_2ya = 1 THEN fle_score ELSE 0 END) AS total_score_2_years_back,
        MAX(curent_date) AS curent_date
    FROM bi_alefdw.fact_learning_experience_silver_mv fles
    WHERE (is_last_7_days = 1 OR is_last_7_days_pp = 1 OR is_last_7_days_ly = 1 OR is_last_7_days_2ya = 1) -- Only process rows relevant to this period type
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12

    UNION ALL

        -- Last 14 Days
    SELECT
        'LAST 14 DAYS' AS period,
       fles.tenant_name,
       fles.school_organisation,
       fles.school_name,
       fles.school_id,
       fles.school_dw_id,
       fles.school_country_name,
       fles.school_city_name,
       fles.school_label,
       fles.school_status,
       fles.grade_name,
       fles.class_gen_subject,
        COUNT(DISTINCT CASE WHEN is_last_14_days = 1 THEN fle_student_dw_id END) AS total_students,
        COUNT(CASE WHEN is_last_14_days = 1 THEN 1 END) AS total_students_days,
        SUM(CASE WHEN is_last_14_days = 1 THEN session_time ELSE 0 END) AS total_time_spent,
        SUM(CASE WHEN is_last_14_days = 1 THEN total_lessons_learned END) AS total_lessons_learned,
        SUM(CASE WHEN is_last_14_days = 1 THEN total_completed_lessons END) AS total_completed_lessons,
        SUM(CASE WHEN is_last_14_days = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score,
        SUM(CASE WHEN is_last_14_days = 1 THEN fle_score ELSE 0 END) AS total_score,
        COUNT(DISTINCT CASE WHEN is_last_14_days_pp = 1 THEN fle_student_dw_id END) AS total_students_previous_period,
        COUNT(CASE WHEN is_last_14_days_pp = 1 THEN 1 END) AS total_students_days_previous_period,
        SUM(CASE WHEN is_last_14_days_pp = 1 THEN session_time ELSE 0 END) AS total_time_spent_previous_period,
        SUM(CASE WHEN is_last_14_days_pp = 1 THEN total_lessons_learned END) AS total_lessons_learned_previous_period,
        SUM(CASE WHEN is_last_14_days_pp = 1 THEN total_completed_lessons END) AS total_completed_lessons_previous_period,
        SUM(CASE WHEN is_last_14_days_pp  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_previous_period,
        SUM(CASE WHEN is_last_14_days_pp= 1 THEN fle_score ELSE 0 END) AS total_score_previous_period,
        COUNT(DISTINCT CASE WHEN is_last_14_days_ly = 1 THEN fle_student_dw_id END) AS total_students_last_year,
        COUNT(CASE WHEN is_last_14_days_ly = 1 THEN 1 END) AS total_students_days_last_year,
        SUM(CASE WHEN is_last_14_days_ly = 1 THEN session_time ELSE 0 END) AS total_time_spent_last_year,
        SUM(CASE WHEN is_last_14_days_ly = 1 THEN total_lessons_learned END) AS total_lessons_learned_last_year,
        SUM(CASE WHEN is_last_14_days_ly = 1 THEN total_completed_lessons END) AS total_completed_lessons_last_year,
        SUM(CASE WHEN is_last_14_days_ly  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_last_year,
        SUM(CASE WHEN is_last_14_days_ly = 1 THEN fle_score ELSE 0 END) AS total_score_last_year,
        COUNT(DISTINCT CASE WHEN is_last_14_days_2ya = 1 THEN fle_student_dw_id END) AS total_students_2_years_back,
        COUNT(CASE WHEN is_last_14_days_2ya = 1 THEN 1 END) AS total_students_days_2_years_back,
        SUM(CASE WHEN is_last_14_days_2ya = 1 THEN session_time ELSE 0 END) AS total_time_spent_2_years_back,
        SUM(CASE WHEN is_last_14_days_2ya = 1 THEN total_lessons_learned END) AS total_lessons_learned_2_years_back,
        SUM(CASE WHEN is_last_14_days_2ya = 1 THEN total_completed_lessons END) AS total_completed_lessons_2_years_back,
        SUM(CASE WHEN is_last_14_days_2ya  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_2_years_back,
        SUM(CASE WHEN is_last_14_days_2ya = 1 THEN fle_score ELSE 0 END) AS total_score_2_years_back,
        MAX(curent_date) AS curent_date
    FROM bi_alefdw.fact_learning_experience_silver_mv fles
    WHERE is_last_14_days = 1 OR is_last_14_days_pp = 1 OR is_last_14_days_ly = 1 OR is_last_14_days_2ya = 1 -- Only process rows relevant to this period type
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12

     UNION ALL

        -- Last 30 Days
    SELECT
        'LAST 30 DAYS' AS period,
       fles.tenant_name,
       fles.school_organisation,
       fles.school_name,
       fles.school_id,
       fles.school_dw_id,
       fles.school_country_name,
       fles.school_city_name,
       fles.school_label,
       fles.school_status,
       fles.grade_name,
       fles.class_gen_subject,
        COUNT(DISTINCT CASE WHEN is_last_30_days = 1 THEN fle_student_dw_id END) AS total_students,
        COUNT(CASE WHEN is_last_30_days = 1 THEN 1 END) AS total_students_days,
        SUM(CASE WHEN is_last_30_days = 1 THEN session_time ELSE 0 END) AS total_time_spent,
        SUM(CASE WHEN is_last_30_days = 1 THEN total_lessons_learned END) AS total_lessons_learned,
        SUM(CASE WHEN is_last_30_days = 1 THEN total_completed_lessons END) AS total_completed_lessons,
        SUM(CASE WHEN is_last_30_days = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score,
        SUM(CASE WHEN is_last_30_days = 1 THEN fle_score ELSE 0 END) AS total_score,
        COUNT(DISTINCT CASE WHEN is_last_30_days_pp = 1 THEN fle_student_dw_id END) AS total_students_previous_period,
        COUNT(CASE WHEN is_last_30_days_pp = 1 THEN 1 END) AS total_students_days_previous_period,
        SUM(CASE WHEN is_last_30_days_pp = 1 THEN session_time ELSE 0 END) AS total_time_spent_previous_period,
        SUM(CASE WHEN is_last_30_days_pp = 1 THEN total_lessons_learned END) AS total_lessons_previous_period,
        SUM(CASE WHEN is_last_30_days_pp = 1 THEN total_completed_lessons END) AS total_completed_lessons_previous_period,
        SUM(CASE WHEN is_last_30_days_pp  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_previous_period,
        SUM(CASE WHEN is_last_30_days_pp = 1 THEN fle_score ELSE 0 END) AS total_score_previous_period,
        COUNT(DISTINCT CASE WHEN is_last_30_days_ly = 1 THEN fle_student_dw_id END) AS total_students_last_year,
        COUNT(CASE WHEN is_last_30_days_ly = 1 THEN 1 END) AS total_students_days_last_year,
        SUM(CASE WHEN is_last_30_days_ly = 1 THEN session_time ELSE 0 END) AS total_time_spent_last_year,
        SUM(CASE WHEN is_last_30_days_ly = 1 THEN total_lessons_learned END) AS total_lessons_learned_last_year,
        SUM(CASE WHEN is_last_30_days_ly = 1 THEN total_completed_lessons END) AS total_completed_lessons_last_year,
        SUM(CASE WHEN is_last_30_days_ly  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_last_year,
        SUM(CASE WHEN is_last_30_days_ly = 1 THEN fle_score ELSE 0 END) AS total_score_last_year,
        COUNT(DISTINCT CASE WHEN is_last_30_days_2ya = 1 THEN fle_student_dw_id END) AS total_students_2_years_back,
        COUNT(CASE WHEN is_last_30_days_2ya = 1 THEN 1 END) AS total_students_days_2_years_back,
        SUM(CASE WHEN is_last_30_days_2ya = 1 THEN session_time ELSE 0 END) AS total_time_spent_2_years_back,
        SUM(CASE WHEN is_last_30_days_2ya = 1 THEN total_lessons_learned END) AS total_lessons_learned_2_years_back,
        SUM(CASE WHEN is_last_30_days_2ya = 1 THEN total_completed_lessons END) AS total_completed_lessons_2_years_back,
        SUM(CASE WHEN is_last_30_days_2ya  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_2_years_back,
        SUM(CASE WHEN is_last_30_days_2ya = 1 THEN fle_score ELSE 0 END) AS total_score_2_years_back,
        MAX(curent_date) AS curent_date
    FROM bi_alefdw.fact_learning_experience_silver_mv fles
    WHERE is_last_30_days = 1 OR is_last_30_days_pp = 1 OR is_last_30_days_ly = 1 OR is_last_30_days_2ya = 1 -- Only process rows relevant to this period type
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12

    UNION ALL

        -- Last 90 Days
    SELECT
        'LAST 90 DAYS' AS period,
       fles.tenant_name,
       fles.school_organisation,
       fles.school_name,
       fles.school_id,
       fles.school_dw_id,
       fles.school_country_name,
       fles.school_city_name,
       fles.school_label,
       fles.school_status,
       fles.grade_name,
       fles.class_gen_subject,
        COUNT(DISTINCT CASE WHEN is_last_90_days = 1 THEN fle_student_dw_id END) AS total_students,
        COUNT(CASE WHEN is_last_90_days = 1 THEN 1 END) AS total_students_days,
        SUM(CASE WHEN is_last_90_days = 1 THEN session_time ELSE 0 END) AS total_time_spent,
        SUM(CASE WHEN is_last_90_days = 1 THEN total_lessons_learned END) AS total_lessons_learned,
        SUM(CASE WHEN is_last_90_days = 1 THEN total_completed_lessons END) AS total_completed_lessons,
        SUM(CASE WHEN is_last_90_days = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score,
        SUM(CASE WHEN is_last_90_days = 1 THEN fle_score ELSE 0 END) AS total_score,
        COUNT(DISTINCT CASE WHEN is_last_90_days_pp = 1 THEN fle_student_dw_id END) AS total_students_previous_period,
        COUNT(CASE WHEN is_last_90_days_pp = 1 THEN 1 END) AS total_students_days_previous_period,
        SUM(CASE WHEN is_last_90_days_pp = 1 THEN session_time ELSE 0 END) AS total_time_spent_previous_period,
        SUM(CASE WHEN is_last_90_days_pp = 1 THEN total_lessons_learned END) AS total_lessons_learned_previous_period,
        SUM(CASE WHEN is_last_90_days_pp = 1 THEN total_completed_lessons END) AS total_completed_lessons_previous_period,
        SUM(CASE WHEN is_last_90_days_pp  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_previous_period,
        SUM(CASE WHEN is_last_90_days_pp = 1 THEN fle_score ELSE 0 END) AS total_score_previous_period,
        COUNT(DISTINCT CASE WHEN is_last_90_days_ly = 1 THEN fle_student_dw_id END) AS total_students_last_year,
        COUNT(CASE WHEN is_last_90_days_ly = 1 THEN 1 END) AS total_students_days_last_year,
        SUM(CASE WHEN is_last_90_days_ly = 1 THEN session_time ELSE 0 END) AS total_time_spent_last_year,
        SUM(CASE WHEN is_last_90_days_ly = 1 THEN total_lessons_learned END) AS total_lessons_learned_last_year,
        SUM(CASE WHEN is_last_90_days_ly = 1 THEN total_completed_lessons END) AS total_completed_lessons_last_year,
        SUM(CASE WHEN is_last_90_days_ly  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_last_year,
        SUM(CASE WHEN is_last_90_days_ly = 1 THEN fle_score ELSE 0 END) AS total_score_last_year,
        COUNT(DISTINCT CASE WHEN is_last_90_days_2ya = 1 THEN fle_student_dw_id END) AS total_students_2_years_back,
        COUNT(CASE WHEN is_last_90_days_2ya = 1 THEN 1 END) AS total_students_days_2_years_back,
        SUM(CASE WHEN is_last_90_days_2ya = 1 THEN session_time ELSE 0 END) AS total_time_spent_2_years_back,
        SUM(CASE WHEN is_last_90_days_2ya = 1 THEN total_lessons_learned END) AS total_lessons_learned_2_years_back,
        SUM(CASE WHEN is_last_90_days_2ya = 1 THEN total_completed_lessons END) AS total_completed_lessons_2_years_back,
        SUM(CASE WHEN is_last_90_days_2ya  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_2_years_back,
        SUM(CASE WHEN is_last_90_days_2ya = 1 THEN fle_score ELSE 0 END) AS total_score_2_years_back,
        MAX(curent_date) AS curent_date
    FROM bi_alefdw.fact_learning_experience_silver_mv fles
    WHERE is_last_90_days = 1 OR is_last_90_days_pp = 1 OR is_last_90_days_ly = 1 OR is_last_90_days_2ya = 1 -- Only process rows relevant to this period type
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12

    UNION ALL

        -- YTD
    SELECT
        'YTD' AS period,
       fles.tenant_name,
       fles.school_organisation,
       fles.school_name,
       fles.school_id,
       fles.school_dw_id,
       fles.school_country_name,
       fles.school_city_name,
       fles.school_label,
       fles.school_status,
       fles.grade_name,
       fles.class_gen_subject,
        COUNT(DISTINCT CASE WHEN is_ytd = 1 THEN fle_student_dw_id END) AS total_students,
        COUNT(CASE WHEN is_ytd = 1 THEN 1 END) AS total_students_days,
        SUM(CASE WHEN is_ytd = 1 THEN session_time ELSE 0 END) AS total_time_spent,
        SUM(CASE WHEN is_ytd = 1 THEN total_lessons_learned END) AS total_lessons_learned,
        SUM(CASE WHEN is_ytd = 1 THEN total_completed_lessons END) AS total_completed_lessons,
        SUM(CASE WHEN is_ytd = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score,
        SUM(CASE WHEN is_ytd = 1 THEN fle_score ELSE 0 END) AS total_score,
        COUNT(DISTINCT CASE WHEN is_ytd_pp = 1 THEN fle_student_dw_id END) AS total_students_previous_period,
        COUNT(CASE WHEN is_ytd_pp = 1 THEN 1 END) AS total_students_days_previous_period,
        SUM(CASE WHEN is_ytd_pp = 1 THEN session_time ELSE 0 END) AS total_time_spent_previous_period,
        SUM(CASE WHEN is_ytd_pp = 1 THEN total_lessons_learned END) AS total_lessons_learned_previous_period,
        SUM(CASE WHEN is_ytd_pp = 1 THEN total_completed_lessons END) AS total_completed_lessons_previous_period,
        SUM(CASE WHEN is_ytd_pp  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_previous_period,
        SUM(CASE WHEN is_ytd_pp = 1 THEN fle_score ELSE 0 END) AS total_score_previous_period,
        COUNT(DISTINCT CASE WHEN is_ytd_ly = 1 THEN fle_student_dw_id END) AS total_students_last_year,
        COUNT(CASE WHEN is_ytd_ly = 1 THEN 1 END) AS total_students_days_last_year,
        SUM(CASE WHEN is_ytd_ly = 1 THEN session_time ELSE 0 END) AS total_time_spent_last_year,
        SUM(CASE WHEN is_ytd_ly = 1 THEN total_lessons_learned END) AS total_lessons_learned_last_year,
        SUM(CASE WHEN is_ytd_ly = 1 THEN total_completed_lessons END) AS total_completed_lessons_last_year,
        SUM(CASE WHEN is_ytd_ly  = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_last_year,
        SUM(CASE WHEN is_ytd_ly = 1 THEN fle_score ELSE 0 END) AS total_score_last_year,
        COUNT(DISTINCT CASE WHEN is_ytd_2ya = 1 THEN fle_student_dw_id END) AS total_students_2_years_back,
        COUNT(CASE WHEN is_ytd_2ya = 1 THEN 1 END) AS total_students_days_2_years_back,
        SUM(CASE WHEN is_ytd_2ya = 1 THEN session_time ELSE 0 END) AS total_time_spent_2_years_back,
        SUM(CASE WHEN is_ytd_2ya = 1 THEN total_lessons_learned END) AS total_lessons_learned_2_years_back,
        SUM(CASE WHEN is_ytd_2ya = 1 THEN total_completed_lessons END) AS total_completed_lessons_2_years_back,
        SUM(CASE WHEN is_ytd_2ya = 1 THEN total_completed_lessons_score END) AS total_completed_lessons_score_2_years_back,
        SUM(CASE WHEN is_ytd_2ya = 1 THEN fle_score ELSE 0 END) AS total_score_2_years_back,
        MAX(curent_date) AS curent_date
    FROM bi_alefdw.fact_learning_experience_silver_mv fles
    WHERE is_ytd = 1 OR is_ytd_pp = 1  OR is_ytd_ly = 1 OR is_ytd_2ya = 1 -- Only process rows relevant to this period type
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
WITH NO SCHEMA BINDING;