CREATE OR REPLACE VIEW bi_alefdw_dev.alain_login_aggregated_view AS
(
SELECT calendar_year_end_date,
        calendar_month_end_date,
        calendar_month_start_date,
        week_start_date,
        week_end_date,
        tenant_dw_id,
        tenant_name,
        content_repository_dw_id,
        content_repository_name,
        academic_year_start_date,
        academic_year_end_date,
        AY,
        student_dw_id as user_dw_id,
        school_dw_id,
        school_name,
        grade_name,
        section_dw_id,
        section_name,
        first_login_date,
        is_active,
        active_days,
        'student' as label
 FROM bi_alefdw.alain_students_login_mv)
UNION
(SELECT calendar_year_end_date,
       calendar_month_end_date,
       calendar_month_start_date,
       week_start_date,
       week_end_date,
       tenant_dw_id,
       tenant_name,
       content_repository_dw_id,
       content_repository_name,
       academic_year_start_date,
       academic_year_end_date,
       AY,
       teacher_dw_id,
       school_dw_id,
       school_name,
       'n/a' as grade_name,
       -10 as section_dw_id,
       'n/a' as section_name,
       first_login_date,
       is_active,
       active_days,
       'teachers' as label
FROM bi_alefdw.alain_teachers_login_mv)
WITH NO SCHEMA BINDING
