CREATE OR REPLACE VIEW bi_alefdw_dev.magg_student_teacher_kpi_historical_dm AS
SELECT
    calendar_year_end_date,
    calendar_month_start_date,
    calendar_month_end_date,
    tenant_dw_id,
    tenant_name,
    content_repository_dw_id,
    content_repository_name,
    academic_year_start_date,
    academic_year_end_date,
    school_dw_id,
    school_name,
    grade_name,
    ay,
    registered_students,
    onboarded_students,
    students_logged_in,
    NULL as registered_teachers,
    NULL as onboarded_teachers,
    NULL as teachers_logged_in,
    reg_school_cumsum,
    reg_student_cumsum,
    onb_school_cumsum,
    onb_student_cumsum,
    NULL as reg_teacher_cumsum,
    NULL as onb_teacher_cumsum,
    ay_rank,
    registered_students_cy,
    onboarded_students_cy,
    registered_students_ay,
    onboarded_students_ay,
    NULL as registered_teachers_cy,
    NULL as onboarded_teachers_cy,
    NULL as registered_teachers_ay,
    NULL as onboarded_teachers_ay,
    inserted_at,
    dense_rank,
    'student' as record_type
FROM bi_alefdw_dev.magg_student_kpi_historical_mv
--WHERE CAST(SPLIT_PART(ay, '-', 2) AS INTEGER) - CAST(SPLIT_PART(ay, '-', 1) AS INTEGER) <= 1
UNION ALL
SELECT
    calendar_year_end_date,
    calendar_month_start_date,
    calendar_month_end_date,
    tenant_dw_id,
    tenant_name,
    content_repository_dw_id,
    content_repository_name,
    academic_year_start_date,
    academic_year_end_date,
    school_dw_id,
    school_name,
    'N/A' as grade_name,
    ay,
    NULL as registered_students,
    NULL as onboarded_students,
    NULL as students_logged_in,
    registered_teachers,
    onboarded_teachers,
    teachers_logged_in,
    NULL as reg_school_cumsum,
    NULL as reg_student_cumsum,
    NULL as onb_school_cumsum,
    NULL as onb_student_cumsum,
    reg_teacher_cumsum,
    onb_teacher_cumsum,
    NULL as ay_rank,
    NULL as registered_students_cy,
    NULL as onboarded_students_cy,
    NULL as registered_students_ay,
    NULL as onboarded_students_ay,
    registered_teachers_cy,
    onboarded_teachers_cy,
    registered_teachers_ay,
    onboarded_teachers_ay,
    inserted_at,
    dense_rank,
    'teacher' as record_type
FROM bi_alefdw_dev.magg_teacher_kpi_historical_mv
--WHERE CAST(SPLIT_PART(ay, '-', 2) AS INTEGER) - CAST(SPLIT_PART(ay, '-', 1) AS INTEGER) <= 1
WITH NO SCHEMA BINDING;